### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by strowk** [projen/projen#1107]
I have used `npx projen new` command and I have got this error: 

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at installPackage (/home/tim/.npm/_npx/789364/lib/node_modules/projen/lib/cli/cmds/new.js:247:32)
    at newProjectFromModule (/home/tim/.npm/_npx/789364/lib/node_modules/projen/lib/cli/cmds/new.js:147:24)
```

Anyone knows what this is about? Could this message made more clear to really explain what should be fixed in a template or setup?

**Comment by eladb** [comment]
@strowk sorry for getting to this only now - can you please put the entire command?
