### ISSUE TITLE
cmake: not found

### ISSUE THREAD

**Issue by strowk** [projen/projen#1108]
I just run `yarn global add projen` and I am getting this error 
```
make: Entering directory '/home/tim/.config/yarn/global/node_modules/cpu-features/build'
  ACTION Configuring dependencies /home/tim/.config/yarn/global/node_modules/cpu-features/deps/cpu_features/build/Makefile
/bin/sh: 1: cmake: not found
make: *** [config_deps.target.mk:13: /home/tim/.config/yarn/global/node_modules/cpu-features/deps/cpu_features/build/Makefile] Error 127
make: Leaving directory '/home/tim/.config/yarn/global/node_modules/cpu-features/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/snap/node/5319/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.11.0-34-generic
```

Is this something important or could be ignored? Is cmake required for projen to work? Is there any documentation about all requirements? 
I am using Ubuntu 20.04

**Comment by Chriscbr** [comment]
Could you please also share the versions of node and yarn you are using?

projen doesn't take any direct dependencies on cmake - so I believe this is some kind of platform-specific issue, related to one of dependencies using the node-gyp package.
