### ISSUE TITLE
Private MAVEN_ENDPOINT not being honored

### ISSUE THREAD

**Issue by damnhandy** [projen/projen#1109]
I'm working with Projen `0.28.33` in a private environment that is behind a proxy and uses an internal NPM and Maven repos. In my `.projenrc.json` file I'm setting the following: 

```javascript
...
  publishToMaven: {
    javaPackage: 'com.mycorp.teamname',
    mavenArtifactId: 'myproject',
    mavenGroupId: 'com.mycorp.teamname',
    mavenEndpoint: 'https://maven.internal.mycorp.com/repository/maven-public/',
...
```
My understanding is that by setting the `mavenEndpoint`, Projen and JSII would resolve Maven artifacts using my internal repo rather trying to resolve them from Maven central. This is what I get when the build fails:

```
🤖 build » compile » docgen | jsii-docgen
Creating assembly in ts for projen-test from /tmp/hGB6Nl (loose: true)
🤖 build » package | env: PATH=/home/developer/proj...
🤖 build » package | jsii-pacmak
[jsii-pacmak] [WARN] Exception occurred, not cleaning up /tmp/npm-packCn4nsW
[jsii-pacmak] [WARN] java failed
Error: All attempts failed. Last error: Command (mvn --quiet --batch-mode deploy -D=altDeploymentRepository=local::default::file:///tmp/npm-packFERuow --settings=user.xml) failed with status 1:
#STDERR> 
#STDOUT> [ERROR] Plugin org.apache.maven.plugins:maven-source-plugin:3.2.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-source-plugin:jar:3.2.1: Could not transfer artifact org.apache.maven.plugins:maven-source-plugin:pom:3.2.1 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-source-plugin/3.2.1/maven-source-plugin-3.2.1.pom: Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.248.215] failed: Connection timed out (Connection timed out) -> [Help 1]
#STDOUT> [ERROR] 
#STDOUT> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
#STDOUT> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
#STDOUT> [ERROR] 
#STDOUT> [ERROR] For more information about the errors and possible solutions, please read the following articles:
#STDOUT> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
#STDOUT> 
    at retry (/home/developer/projen-test/node_modules/jsii-pacmak/lib/util.js:70:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Java.build (/home/developer/projen-test/node_modules/jsii-pacmak/lib/targets/java.js:303:9)
    at async /home/developer/projen-test/node_modules/jsii-pacmak/lib/targets/java.js:60:17
    at async Function.make (/home/developer/projen-test/node_modules/jsii-pacmak/lib/util.js:186:36)
    at async JavaBuilder.buildModules (/home/developer/projen-test/node_modules/jsii-pacmak/lib/targets/java.js:58:35)
    at async Promise.all (index 2)
    at async Object.pacmak (/home/developer/projen-test/node_modules/jsii-pacmak/lib/index.js:56:9)
```

I'm wondering if this isn't the right setting or not, or if what I am trying to do is even supported at this time. Please advise.

**Comment by zhelyan** [comment]
Any plans to honour the local maven settings if present?

**Comment by mrgrain** [comment]
> Any plans to honour the local maven settings if present?
> 
> @eladb

Thanks for the report. Would you mind opening a new issue with a reproduction and/or example how this would work without projen and possibly API suggestion.

Asking because this issue is a) really really old and b) the publishing settings are definitely only for publishing. 

Oh and elad is no longer a maintainer. 😉

**Comment by eladb** [comment]
👋
