### ISSUE TITLE
projen new fails when no git global author identity is set

### ISSUE THREAD

**Issue by meeuw** [projen/projen#1287]
#### Description

I use different git author identities (private / work e-mail address for my commits). I do this by leaving `user.email` and `user.name` unset from my `~/.gitconfig`. This is the default configuration but git reminds you of setting it at your first comment when unset:
```
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.
```

For me this prompt is a reminder to run these commands without the `--global` flag for a certain repository.

Projen is unable to handle this prompt.

#### How to reproduce

1. Remove your email/name from `~/.gitconfig` (or temporary remove `~/.gitconfig`)
2. Run `npx projen new awscdk-app-ts`

#### Actual result

```
$ npx projen new awscdk-app-ts
Need to install the following packages:
  projen
Ok to proceed? (y) y
👾 Project definition file was created at /tmp/.projenrc.js
👾 warning: failed to clean up generated files: Error: EACCES: permission denied, scandir '/tmp/systemd-private-8508d66f569e4d9bac23633542ff0789-ModemManager.service-MuJzot'
    at Object.readdirSync (node:fs:1390:3)
    at GlobSync._readdir (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/glob/sync.js:285:46)
    at GlobSync._readdirInGlobStar (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/glob/sync.js:264:20)
    at GlobSync._readdir (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/glob/sync.js:273:17)
    at GlobSync._processGlobStar (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/glob/sync.js:347:22)
    at GlobSync._process (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/glob/sync.js:127:10)
    at GlobSync._processGlobStar (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/glob/sync.js:380:10)
    at GlobSync._process (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/glob/sync.js:127:10)
    at new GlobSync (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/glob/sync.js:45:10)
    at Function.globSync [as sync] (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/glob/sync.js:23:10)
yarn install v1.22.10
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 30.09s.

> tmp@0.0.0 eslint
> npx projen eslint

Initialized empty Git repository in /tmp/.git/
Error: Command failed: git commit --allow-empty -m "chore: project created with projen"
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'meeuw@prodesk.(none)')

    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.exec (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/util.js:15:19)
    at git (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js:224:37)
    at newProject (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js:227:9)
    at Object.handler (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js:60:34)
    at Object.runCommand (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:446:48)
    at Object.parseArgs [as _parseArgs] (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:2697:57)
    at Object.runCommand (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:410:36)
    at Object.parseArgs [as _parseArgs] (/home/meeuw/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:2697:57) {
  status: 128,
  signal: null,
  output: [
    null,
    null,
    <Buffer 41 75 74 68 6f 72 20 69 64 65 6e 74 69 74 79 20 75 6e 6b 6e 6f 77 6e 0a 0a 2a 2a 2a 20 50 6c 65 61 73 65 20 74 65 6c 6c 20 6d 65 20 77 68 6f 20 79 6f ... 281 more bytes>
  ],
  pid: 4385,
  stdout: null,
  stderr: <Buffer 41 75 74 68 6f 72 20 69 64 65 6e 74 69 74 79 20 75 6e 6b 6e 6f 77 6e 0a 0a 2a 2a 2a 20 50 6c 65 61 73 65 20 74 65 6c 6c 20 6d 65 20 77 68 6f 20 79 6f ... 281 more bytes>
}
```

#### Expected result

```
👾 Project definition file was created at /tmp/dmtest/.projenrc.js
yarn install v1.22.10
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 26.38s.

> dmtest@0.0.0 eslint
> npx projen eslint

Reinitialized existing Git repository in /tmp/dmtest/.git/
[master (root-commit) 2d52c3a] chore: project created with projen
 22 files changed, 7336 insertions(+)
 create mode 100644 .eslintrc.json
 create mode 100644 .gitattributes
 create mode 100644 .github/pull_request_template.md
 create mode 100644 .github/workflows/build.yml
 create mode 100644 .github/workflows/pull-request-lint.yml
 create mode 100644 .github/workflows/stale.yml
 create mode 100644 .github/workflows/upgrade.yml
 create mode 100644 .gitignore
 create mode 100644 .mergify.yml
 create mode 100644 .npmignore
 create mode 100644 .projen/deps.json
 create mode 100644 .projen/tasks.json
 create mode 100644 .projenrc.js
 create mode 100644 LICENSE
 create mode 100644 README.md
 create mode 100644 cdk.json
 create mode 100644 package.json
 create mode 100644 src/main.ts
 create mode 100644 test/main.test.ts
 create mode 100644 tsconfig.dev.json
 create mode 100644 tsconfig.json
 create mode 100644 yarn.lock
```

#### Workaround

Pre-create the git repository and set the email/user before running `projen new`

**Comment by Chriscbr** [comment]
@meeuw It should be possible to disable creating the git repository by passing `--no-git`.

I'm curious if this issue also happens with other project-creation tools (e.g. what happens if you try running `npx create-react-app my-app`?) On my development machine it auto-fills some defaults if I don't have my gitconfig set, but it's possible that behavior is dependent on my OS or git version. (I'm running macOS 11.6 with git 2.33.1).

I think the current defaults/options are ok, but I'd be open to adding a log message that says e.g. "Initializing git repository for your project (use --no-git to disable this)...".

**Comment by meeuw** [comment]
create-react-app fails to initialize the git repository and then deletes the .git directory:
```
Git commit not created Error: Command failed: git commit -m "Initialize project using Create React App"
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at tryGitCommit (/tmp/my-app/node_modules/react-scripts/scripts/init.js:62:5)
    at module.exports (/tmp/my-app/node_modules/react-scripts/scripts/init.js:352:25)
    at [eval]:3:14
    at Script.runInThisContext (node:vm:129:12)
    at Object.runInThisContext (node:vm:305:38)
    at node:internal/process/execution:81:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:80:60) {
  status: 128,
  signal: null,
  output: [ null, null, null ],
  pid: 10636,
  stdout: null,
  stderr: null
}
Removing .git directory...
```
