### ISSUE TITLE
CDK integration tests fail with `Emit skipped` in `awscdk-construct` projects

### ISSUE THREAD

**Issue by eladb** [projen/projen#1299]
Root cause: when running `ts-node` in `awscdk-construct` projects, it defaults to use `tsconfig.json` which is generated by JSII and does not include the `test/` tree. 

Solution: we need to tell the CDK to run `ts-node` with `tsconfig.dev.json`.

Reported by @jumic - repro: https://github.com/jumic/projen-integ-test

**Comment by jumic** [comment]
Thank you very much for analysing this issue and for providing the fix, @eladb.

I updated my project to the new version (my example repo is updated, too).

First, I removed the dependency to `ts-node` because it should be added automatically after your fix. However projen fails to add the dependency.
```
➜  projen-integ-test git:(main) ✗ pj
👾 default | node .projenrc.js
/Users/julian/dev/projen-integ-test/node_modules/projen/lib/dependencies.js:85
            throw new Error(msg);
            ^

Error: there is no dependency defined on "ts-node"
    at Dependencies.getDependency (/Users/julian/dev/projen-integ-test/node_modules/projen/lib/dependencies.js:85:19)
    at new IntegrationTest (/Users/julian/dev/projen-integ-test/node_modules/projen/lib/awscdk/integration-test.js:29:27)
    at AutoDiscover.autoDiscoverIntegrationTests (/Users/julian/dev/projen-integ-test/node_modules/projen/lib/awscdk/auto-discover.js:42:13)
    at new AutoDiscover (/Users/julian/dev/projen-integ-test/node_modules/projen/lib/awscdk/auto-discover.js:24:14)
    at new AwsCdkConstructLibrary (/Users/julian/dev/projen-integ-test/node_modules/projen/lib/awscdk/awscdk-construct.js:60:13)
    at Object.<anonymous> (/Users/julian/dev/projen-integ-test/.projenrc.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
👾 Synthesis failed: Task "default" failed when executing "node .projenrc.js" (cwd: /Users/julian/dev/projen-integ-test)
```

`getDependency` should add the dependency if it is missing.
https://github.com/projen/projen/blob/87fbb27f7f5402363bec5130f1904517ae8efbf3/src/awscdk/integration-test.ts#L78-L80

The underlying method throws an error if the dependency is missing. Hence, it fails and it doesn't add the dependency. Probably we need a similar method that doesn't throw an error if the dependency is missing. Maybe a public version of `tryGetDependencyIndex`.
https://github.com/projen/projen/blob/87fbb27f7f5402363bec5130f1904517ae8efbf3/src/dependencies.ts#L82-L95

I added `ts-node` manually again to continue.

I can see that parameter ` -P tsconfig.dev.json` was added to command `ts-node`. However, I still get the original error. I will also look into the configuration again to see if I find the root cause.
```
👾 build » test » integ:example:assert | cdk synth --app "ts-node test/example.integ.ts -P tsconfig.dev.json" --no-version-reporting --context aws-cdk:enableDiffNoFail=true --context @aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId=true --context @aws-cdk/core:enableStackNameDuplicates=true --context @aws-cdk/core:stackRelativeExports=true --context @aws-cdk/aws-ecr-assets:dockerIgnoreSupport=true --context @aws-cdk/aws-secretsmanager:parseOwnedSecretName=true --context @aws-cdk/aws-kms:defaultKeyPolicies=true --context @aws-cdk/aws-s3:grantWriteWithoutAcl=true --context @aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount=true --context @aws-cdk/aws-rds:lowercaseDbIdentifier=true --context @aws-cdk/aws-efs:defaultEncryptionAtRest=true --context @aws-cdk/aws-lambda:recognizeVersionProps=true --context @aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021=true --context @aws-cdk/core:newStyleStackSynthesis=true -o test/.tmp/example.integ/synth.cdk.out > /dev/null
/Users/julian/dev/projen-integ-test/node_modules/ts-node/src/index.ts:944
          throw new TypeError(`${relative(cwd, fileName)}: Emit skipped`);
                ^
TypeError: test/example.integ.ts: Emit skipped
    at getOutput (/Users/julian/dev/projen-integ-test/node_modules/ts-node/src/index.ts:944:17)
    at Object.compile (/Users/julian/dev/projen-integ-test/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/Users/julian/dev/projen-integ-test/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/julian/dev/projen-integ-test/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at main (/Users/julian/dev/projen-integ-test/node_modules/ts-node/src/bin.ts:331:12)
    at Object.<anonymous> (/Users/julian/dev/projen-integ-test/node_modules/ts-node/src/bin.ts:482:3)
Subprocess exited with error 1
👾 Task "build » test » integ:example:assert" failed when executing "cdk synth --app "ts-node test/example.integ.ts -P tsconfig.dev.json" --no-version-reporting --context aws-cdk:enableDiffNoFail=true --context @aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId=true --context @aws-cdk/core:enableStackNameDuplicates=true --context @aws-cdk/core:stackRelativeExports=true --context @aws-cdk/aws-ecr-assets:dockerIgnoreSupport=true --context @aws-cdk/aws-secretsmanager:parseOwnedSecretName=true --context @aws-cdk/aws-kms:defaultKeyPolicies=true --context @aws-cdk/aws-s3:grantWriteWithoutAcl=true --context @aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount=true --context @aws-cdk/aws-rds:lowercaseDbIdentifier=true --context @aws-cdk/aws-efs:defaultEncryptionAtRest=true --context @aws-cdk/aws-lambda:recognizeVersionProps=true --context @aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021=true --context @aws-cdk/core:newStyleStackSynthesis=true -o test/.tmp/example.integ/synth.cdk.out > /dev/null" (cwd: /Users/julian/dev/projen-integ-test)
```

**Comment by eladb** [comment]
apologies for this crappy work:

1. The ts-node command line should have `-P` before the entrypoint.
2. We should do something like `tryGetDependency()`.

On it.
