### ISSUE TITLE
Projen upgrade workflows failing with: TypeError: AwsCdkConstructLibrary is not a constructor

### ISSUE THREAD

**Issue by ayush987goyal** [projen/projen#1436]
I have a couple of CDK construct libraries created with projen whose upgrade workflows are failing with the following error:

```
👾 upgrade | npx projen
👾 default | node .projenrc.js
/__w/umami-analytics-construct/umami-analytics-construct/.projenrc.js:2
const project = new AwsCdkConstructLibrary({
                ^

TypeError: AwsCdkConstructLibrary is not a constructor
    at Object.<anonymous> (/__w/umami-analytics-construct/umami-analytics-construct/.projenrc.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

Is there a workaround for a fix?

Failed actions:
1. https://github.com/ayush987goyal/umami-analytics-construct/runs/4663154365?check_suite_focus=true
2. https://github.com/ayush987goyal/verdaccio-service-construct/runs/4663247618?check_suite_focus=true

**Comment by eladb** [comment]
You'll need to modify your projenrc to import `awscdk.AwsCdkConstructLibrary` instead

**Comment by ayush987goyal** [comment]
Thanks @eladb . Locally upgrading projen and with your suggestion, I was able to resolve the issue.
