### ISSUE TITLE
New java application from custom extension fails to initialize

### ISSUE THREAD

**Issue by msessa** [projen/projen#1449]
`projen new --from=..` command fails when initializing a java application that uses options derived from the built-in types provided by projen.

Given a class like this packaged in a custom jsii module:
```typescript
import { java } from 'projen';

export interface ExtendedJavaProjectOptions extends java.JavaProjectOptions {
  readonly dummy?: string;
}

/**
 * Example extended class
 *
 * @pjid extended-java-app
 */
export class ExtendedJavaProject extends java.JavaProject {
  constructor(options: ExtendedJavaProjectOptions) {
    super(options)
  }
}
```

when attempting to use it via
```
npx projen@latest new --from my-extension@/path/to/my-extension@0.0.0.jsii.tgz extended-java-app
```

projen fails with:
```
java-app-temp@ /Users/msessa/Work/private-git/java-app-temp
└── projen@0.47.15

👾 installing external module @service-victoria/my-extension@/Users/msessa/Work/private-git/my-extension/dist/js/my-extension@0.0.0.jsii.tgz...

up to date, audited 71 packages in 1s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/Users/msessa/Work/private-git/java-app-temp/node_modules/projen/lib/java/projenrc.js:145
    return [jsiiType.namespace, jsiiType.name].filter(x => x).join('.');
                     ^

TypeError: Cannot read properties of undefined (reading 'namespace')
    at toJavaFullTypeName (/Users/msessa/Work/private-git/java-app-temp/node_modules/projen/lib/java/projenrc.js:145:22)
    at Projenrc.generateProjenrc (/Users/msessa/Work/private-git/java-app-temp/node_modules/projen/lib/java/projenrc.js:86:43)
    at new Projenrc (/Users/msessa/Work/private-git/java-app-temp/node_modules/projen/lib/java/projenrc.js:40:14)
    at new JavaProject (/Users/msessa/Work/private-git/java-app-temp/node_modules/projen/lib/java/java-project.js:29:29)
    at new ExtendedJavaProject (/Users/msessa/Work/private-git/java-app-temp/node_modules/@service-victoria/my-extension/lib/java/extended-java-app.js:18:9)
    at evalmachine.<anonymous>:1:28
    at Script.runInContext (node:vm:139:12)
    at Object.runInContext (node:vm:289:6)
    at createProject (/Users/msessa/Work/private-git/java-app-temp/node_modules/projen/lib/projects.js:76:8)
    at Function.createProject (/Users/msessa/Work/private-git/java-app-temp/node_modules/projen/lib/projects.js:31:9)
```

**Comment by msessa** [comment]
It seems like the issue is caused by:
https://github.com/projen/projen/blob/28f87cb44d555f8c093762178b6e315838cd08f0/src/java/projenrc.ts#L129

which attempts to lookup option types definitions within the extension's `.jsii`, that instead exist only within projen's `.jsii`.

**Comment by msessa** [comment]
Possible solutions I could think of are:

1- Degrade gracefully:
```typescript
        try {
          optionFqns[option.name] = toJavaFullTypeName(jsiiManifest.types[option.fqn]);
        } catch {}
```

2- Make a guess
```typescript
        if (jsiiManifest.types[option.fqn] !== undefined) {
          optionFqns[option.name] = toJavaFullTypeName(jsiiManifest.types[option.fqn]);
        } else {
          const name = option.fqn.split('.')[-1];
          const namesspace = option.fqn.split('.')[-2];
          optionFqns[option.name] = toJavaFullTypeName({ name, namesspace });
        }
```

3- Detect that we're working with an extension and merge options from projen's `.jsii`, but I think this could get hairy
