### ISSUE TITLE
react-ts: Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension

### ISSUE THREAD

**Issue by moltar** [projen/projen#1463]
Seems like projen stops working within the `react-ts` and `.projenrc.ts` setup:

```
❯ pj
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
(node:24305) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
xyz/projen-react/.projenrc.ts:1
import { web, TextFile } from "projen";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Module.m._compile (xyz/projen-react/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (xyz/projen-react/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at main (xyz/projen-react/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (xyz/projen-react/node_modules/ts-node/src/bin.ts:288:3)
👾 Synthesis failed: Task "default" failed when executing "ts-node --project tsconfig.dev.json .projenrc.ts" (cwd: xyz/projen-react)
```

**Comment by kado-yasuyuki** [comment]
The same error occurs when the following commands
- `npx projen new nextjs-ts --projenrc-ts`
- `yarn projen`

I think it will work if projen overrides the compilerOptions for ts-node.
https://github.com/TypeStrong/ts-node#commonjs

By the way, I have successfully `yarn projen` in the following ways.

Set `compilerOptions.module` to `CommonJS` as follows

```ts
// .projenrc.ts file
import { web } from "projen";
const project = new web.NextJsTypeScriptProject({
  defaultReleaseBranch: "main",
  name: "nextjs-ts-test",
  projenrcTs: true,
  tsconfigDev: {
    compilerOptions: {
      module: "CommonJS" // <- here
    }
  }
```

In order to make the first `yarn projen` successful, we have to manually modify the `tsconfig.dev.json` file. `tsconfig.dev.json` file is read-only, so we need to `chmod` it.

```
- "module": "esnext",
+ "module": "CommonJS",
```

**Comment by moltar** [comment]
[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by pgollucci** [comment]
https://github.com/projen/projen/issues/1463

**Comment by marciocadev** [comment]
react-ts continue give this error, this change should be made in `ReactTypeScriptProject` not `NextJsTypeScriptProject`

**Comment by kreempuff** [comment]
Experiencing this on version `0.81.4`
