### ISSUE TITLE
Can't create License with copyrightOwner for AwsCdkConstructLibrary

### ISSUE THREAD

**Issue by am29d** [projen/projen#1505]
I want to add MIT-0 license with my custom `copyrightOwner` for my `AwsCdkConstructLibrary` project. 

I have created a new project with `projen new awscdk-construct` and added a license in `.projenrc.js`

```typescript
const { awscdk, License } = require('projen');
const project = new awscdk.AwsCdkConstructLibrary({
  author: 'Alexander Melnyk',
  authorAddress: 'REDACTED',
  cdkVersion: '2.1.0',
  defaultReleaseBranch: 'main',
  name: 'projen-test',
  repositoryUrl: 'https://github.com/am29d/projen-test.git',
});

new License(project, {
  spdx: 'MIT-0',
  copyrightOwner: 'My Org',
});
project.synth();

```

when I run `yarn project` I get error:

```
/Users/.../projen-test/node_modules/projen/lib/file.js:34
            throw new Error(`there is already a file under ${path.relative(project.root.outdir, this.absolutePath)}`);
            ^

Error: there is already a file under LICENSE
    at new FileBase (/Users/.../projen-test/node_modules/projen/lib/file.js:34:19)
    at new License (/Users/.../projen-test/node_modules/projen/lib/license.js:17:9)
    at Object.<anonymous> (/Users/.../projen-test/.projenrc.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
👾 Synthesis failed: Task "default" failed when executing "node .projenrc.js" (cwd: /Users/../projen-test)
error Command failed with exit code 1.
```

When I delete the `LICENSE` file that was generated previously, I get the same error. I can set `licensed: false` property in my project, but that will set `UNLICENSED` flag in my `package.json` and thus all the packages on npmjs or pypi. I need the `MIT-0` license.

**Comment by am29d** [comment]
Of course I have found the solution few minutes after I have submitted this issue 😔. 

I have used projen version `0.40.8` and the `copyrightOwner` property was not available for `AwsCdkConstructLibrary`. After projen upgrade to `0.50.17` I no longer need the License object and can specificy the license and the owner inside the project definition.


Working example:

```
const { awscdk } = require('projen');
const project = new awscdk.AwsCdkConstructLibrary({
  author: 'Alexander Melnyk',
  authorAddress: 'REDACTED',
  cdkVersion: '2.1.0',
  defaultReleaseBranch: 'main',
  name: 'projen-test',
  copyrightOwner: 'My Org',
  license: 'MIT-0',
  repositoryUrl: 'https://github.com/am29d/projen-test.git',
});


project.synth();
```
