### ISSUE TITLE
npx projen new awscdk-app-ts returns TypeError: Invalid Version: 2.23.0..1

### ISSUE THREAD

**Issue by lrevnic** [projen/projen#1518]
Hello,

When using the latest projen version, executing npx projen new awscdk-app-ts on a Windows system I'm consistently getting 
TypeError: Invalid Version: **2.23.0..1**
    at new SemVer (C:\Workspace\projen\node_modules\projen\node_modules\semver\classes\semver.js:38:13)
    at compare (C:\Workspace\projen\node_modules\projen\node_modules\semver\functions\compare.js:3:3)
    at Object.gte (C:\Workspace\projen\node_modules\projen\node_modules\semver\functions\gte.js:2:30)
    at initProject (C:\Workspace\projen\node_modules\projen\lib\cli\cmds\new.js:261:34)
    at Object.handler (C:\Workspace\projen\node_modules\projen\lib\cli\cmds\new.js:87:36)
    at Object.runCommand (C:\Workspace\projen\node_modules\projen\node_modules\yargs\build\index.cjs:446:48)
    at Object.parseArgs [as _parseArgs] (C:\Workspace\projen\node_modules\projen\node_modules\yargs\build\index.cjs:2697:57)
    at Object.runCommand (C:\Workspace\projen\node_modules\projen\node_modules\yargs\build\index.cjs:410:36)
    at Object.parseArgs [as _parseArgs] (C:\Workspace\projen\node_modules\projen\node_modules\yargs\build\index.cjs:2697:57)

.projenrc.js is the default one:
const { awscdk } = require('projen');
const project = new awscdk.AwsCdkTypeScriptApp({
  cdkVersion: '2.1.0',
  defaultReleaseBranch: 'main',
  name: 'infra-ts',

  // deps: [],                /* Runtime dependencies of this module. */
  // description: undefined,  /* The description is just a string that helps people understand the purpose of the package. */
  // devDeps: [],             /* Build dependencies for this module. */
  // packageName: undefined,  /* The "name" in package.json. */
});
project.synth();

npm list: 
+-- @balena/dockerignore@1.0.2 extraneous
+-- @iarna/toml@2.2.5 extraneous
+-- @oozcitak/dom@1.15.8 extraneous
+-- @oozcitak/infra@1.0.8 extraneous
+-- @oozcitak/url@1.0.4 extraneous
+-- @oozcitak/util@8.3.8 extraneous
+-- @types/jest@27.4.0
+-- @types/node@12.20.41
+-- @typescript-eslint/eslint-plugin@5.9.1
+-- @typescript-eslint/parser@5.9.1
+-- aws-cdk-lib@2.5.0
+-- aws-cdk@2.5.0
+-- case@1.6.3 extraneous
+-- constructs@10.0.31
+-- conventional-changelog-config-spec@2.1.0 extraneous
+-- esbuild@0.14.11
+-- eslint-import-resolver-node@0.3.6
+-- eslint-import-resolver-typescript@2.5.0
+-- eslint-plugin-import@2.25.4
+-- eslint@8.6.0
+-- interpret@1.4.0 extraneous
+-- jest-junit@13.0.0
+-- jest@27.4.7
+-- json-schema@0.4.0
+-- jsonschema@1.4.0 extraneous
+-- npm-check-updates@12.1.0
+-- projen@0.50.24
+-- rechoir@0.6.2 extraneous
+-- shelljs@0.8.5 extraneous
+-- shx@0.3.4 extraneous
+-- ts-jest@27.1.2
+-- ts-node@9.1.1
+-- typescript@4.5.4
`-- xmlbuilder2@2.4.1 extraneous

**Comment by lrevnic** [comment]
Looks like the problem was fixed in projen 0.50.25 available here https://github.com/projen/projen/releases/tag/v0.50.25
