### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED when doing `yarn release`

### ISSUE THREAD

**Issue by dan-lind** [projen/projen#1571]
I haven't updated projen in quite some time, had 0.29.8 before today for my cdk library project. 
I updated my .projenrc.js with the latest versions
```
  cdkVersion: '1.140.0',
  projenVersion: '0.52.4',
```
Ran `npx projen` and was made aware I had an old npm version, so I updated that as well. 
`New major version of npm available! 7.18.1 -> 8.3.2`

But after making my code changes and running `yarn release` per usual, after successfully running the unit tests I'm seeing this error
```
Ran all test suites.
👾 release » build » test » eslint | eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test build-tools .projenrc.js

Oops! Something went wrong! :(

ESLint: 8.7.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/glob-util' is not defined by "exports" in /home/dxxjmb/git/cdk-constructs/node_modules/eslint/package.json
    at new NodeError (node:internal/errors:363:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:335:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:560:3)
    at resolveExports (node:internal/modules/cjs/loader:476:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:516:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:913:27)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (/home/dxxjmb/git/cdk-constructs/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/dxxjmb/git/cdk-constructs/node_modules/eslint-plugin-import/lib/rules/no-unused-modules.js:43:34)
👾 Task "release » build » test » eslint" failed when executing "eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test build-tools .projenrc.js" (cwd: /home/dxxjmb/git/cdk-constructs)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What to do?

**Comment by dan-lind** [comment]
Looks like this was resolved by running `npx projen upgrade`
