### ISSUE TITLE
`projen new` fails with `Error: Cannot find module 'typescript/.jsii'`

### ISSUE THREAD

**Issue by moltar** [projen/projen#1613]
```
❯ npx projen@latest new --from typescript --projenrc-ts
npx: installed 65 in 3.397s
/prj/dir
└── projen@0.52.28

Wrote to /prj/dir/package.json:

{
  "name": "projen-foo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "typescript": "4.5.5",
    "projen": "0.52.28"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "xxx",
  "license": "ISC"
}


👾 installing external module typescript...
+ typescript@4.5.5
updated 1 package and audited 66 packages in 1.143s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Error: Cannot find module 'typescript/.jsii'
Require stack:
- /Users/xyz/.npm/_npx/9788/lib/node_modules/projen/lib/cli/cmds/new.js
- /Users/xyz/.npm/_npx/9788/lib/node_modules/projen/node_modules/yargs/index.cjs
- /Users/xyz/.npm/_npx/9788/lib/node_modules/projen/lib/cli/index.js
- /Users/xyz/.npm/_npx/9788/lib/node_modules/projen/bin/projen
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at initProjectFromModule (/Users/xyz/.npm/_npx/9788/lib/node_modules/projen/lib/cli/cmds/new.js:176:44)
    at Object.handler (/Users/xyz/.npm/_npx/9788/lib/node_modules/projen/lib/cli/cmds/new.js:96:20)
    at Object.runCommand (/Users/xyz/.npm/_npx/9788/lib/node_modules/projen/node_modules/yargs/build/index.cjs:446:48)
    at Object.parseArgs [as _parseArgs] (/Users/xyz/.npm/_npx/9788/lib/node_modules/projen/node_modules/yargs/build/index.cjs:2697:57)
    at Function.get [as argv] (/Users/xyz/.npm/_npx/9788/lib/node_modules/projen/node_modules/yargs/build/index.cjs:2651:25)
    at main (/Users/xyz/.npm/_npx/9788/lib/node_modules/projen/lib/cli/index.js:46:21)
    at Object.<anonymous> (/Users/xyz/.npm/_npx/9788/lib/node_modules/projen/lib/cli/index.js:63:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/xyz/.npm/_npx/9788/lib/node_modules/projen/lib/cli/cmds/new.js',
    '/Users/xyz/.npm/_npx/9788/lib/node_modules/projen/node_modules/yargs/index.cjs',
    '/Users/xyz/.npm/_npx/9788/lib/node_modules/projen/lib/cli/index.js',
    '/Users/xyz/.npm/_npx/9788/lib/node_modules/projen/bin/projen'
  ]
}
```

**Comment by moltar** [comment]
Ah, never mind, it's:

```sh
npx projen@latest new typescript
```

not

```sh
npx projen@latest new --from typescript
```

... but it's still actually confusing DX/UX
