### ISSUE TITLE
Projen build fails on react typescript

### ISSUE THREAD

**Issue by alexforsyth** [projen/projen#1635]
## Steps to Reproduce:

Seems like we're having some issues building react-typescript. Projen version: `0.52.40`.

```
 projen new react-ts --projenrc-ts --no-post
 yarn
 yarn build
```

results in:
```
Task "build » default" failed when executing "ts-node --project tsconfig.dev.json .projenrc.ts" 
```

If I set the `  "type": "module",` in the package.json then build errors with:
```
❯ yarn build
yarn run v1.22.10
$ npx projen build
👾 build » default | ts-node --project tsconfig.dev.json .projenrc.ts
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /...../react-projen/.projenrc.ts
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:104:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:31)
    at Loader.import (internal/modules/esm/loader.js:176:17)
    at Object.loadESM (internal/process/esm_loader.js:68:5)
👾 Task "build » default" failed when executing "ts-node --project tsconfig.dev.json .projenrc.ts" 
```

**Comment by Chriscbr** [comment]
Possible workaround:

```
  tsconfig: {
    compilerOptions: {
      module: "CommonJS",
    }
  }
```

**Comment by alexforsyth** [comment]
Another possible workaround:
```
  tsconfig: {
    include: ["src/**/loaders.d.ts"],
    compilerOptions: {
      module: "CommonJS",
      noUnusedLocals: false,
      noImplicitAny: false,
    }
  }
  ```
  with the loaders.d.ts
  ```
  declare module '*.svg' {
    const content: any;
    export default content;
}
  ```

**Comment by pgollucci** [comment]
Looking into this one actively
