### ISSUE TITLE
Creating new project with node v12 fails

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#1740]
Minimal repro:

```
$ mkdir -p /tmp/projen-test
$ cd /tmp/projen-test
$ npx projen@latest --version
0.54.8
$ node --version
12.22.0
$ npx projen@latest new node
npx: installed 65 in 3.405s
👾 Project definition file was created at /private/tmp/foo/.projenrc.js
yarn install v1.22.18
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
child_process.js:674
    throw err;
    ^

Error: Command failed: yarn install --check-files
error yaml@2.0.0: The engine "node" is incompatible with this module. Expected version ">= 14". Got "12.22.0"
error Found incompatible module.

    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at Object.exec (/Users/rybickic/.npm/_npx/20800/lib/node_modules/projen/lib/util.js:15:19)
    at NodePackage.installDependencies (/Users/rybickic/.npm/_npx/20800/lib/node_modules/projen/lib/javascript/node-package.js:661:16)
    at NodePackage.postSynthesize (/Users/rybickic/.npm/_npx/20800/lib/node_modules/projen/lib/javascript/node-package.js:300:18)
    at NodeProject.synth (/Users/rybickic/.npm/_npx/20800/lib/node_modules/projen/lib/project.js:281:22)
    at evalmachine.<anonymous>:12:20
    at Script.runInContext (vm.js:130:18)
    at Object.runInContext (vm.js:293:6)
    at createProject (/Users/rybickic/.npm/_npx/20800/lib/node_modules/projen/lib/projects.js:74:8)
```

This is causing an integration test to fail, which is causing new development builds to fail as well (example: https://github.com/projen/projen/pull/1721).

Workaround: add the option `--package-manager="npm"` when running `projen new`.

It looks like `yarn` is not respecting that `yaml` should be a bundled dependency of projen. I think this is related to the fact that package.json is listing these dependencies as both `bundleDependencies` and regular runtime `dependencies`.

**Comment by Chriscbr** [comment]
Confirmed that newly released version of projen (v0.54.9) fixes this.
