### ISSUE TITLE
JSII project won't build from a clean creation

### ISSUE THREAD

**Issue by mbonig** [projen/projen#1801]
After creating a new JSII project (`pj new jsii`) and then running a `yarn build`, tests fail with the following error:

```
ts-jest[versions] (WARN) Version 28.0.1 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=27.0.0 <28.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.
 FAIL  test/hello.test.ts
  ● Test suite failed to run

    ● Invalid return value:
      Code transformer's `process` method must return an object containing `code` key 
      with processed string. If `processAsync` method is implemented it must return 
      a Promise resolving to an object containing `code` key with processed string.
      Code Transformation Documentation:
      https://jestjs.io/docs/code-transformation
    

      at ScriptTransformer._buildTransformResult (node_modules/@jest/transform/build/ScriptTransformer.js:504:15)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:623:17)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:760:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:817:19)

```

I turned on debugging for ts-jest but can't make heads or tails of the messages and what could be causing this.

**Comment by Chriscbr** [comment]
I think this is caused by the new version of jest. As a workaround changing the jest version should fix it:

```
jestOptions: {
    jestVersion: '^27',
  },
```

Do you think we should make this the default for now?

**Comment by mbonig** [comment]
yup, that cleared the error. I can submit a PR if you'd like, but where would you recommend doing this? I assume here?

https://github.com/projen/projen/blob/a64180a673f1d436f3515148e89cc3d5b9b0590c/src/javascript/jest.ts#L594

how about: 

```
const jestDep = options.jestVersion
      ? `jest@${options.jestVersion}`
      : "jest@27"; // defaulting to 27 until issues are resolved
```

??

**Comment by Chriscbr** [comment]
Sure 👍

**Comment by mbonig** [comment]
Thanks!
