### ISSUE TITLE
Error creating a new project

### ISSUE THREAD

**Issue by juanledesma84** [projen/projen#1820]
Hi there!

It's my first time using Projen. When I create a new project I get an error, but I see that the structure and files were created. I was looking for information about it, but I did not find anything, for this reason I create this issue.

OS: MacOS 12.3.1
Shell: zsh

`$ npx projen new awscdk-app-ts
👾 Project definition file was created at /Users/xxx/projenTest/.projenrc.js
node:child_process:905
    throw err;
    ^

Error: Command failed: yarn install --check-files
/bin/sh: yarn: command not found

    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at Object.exec (/Users/xxx/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/util.js:15:19)
    at NodePackage.installDependencies (/Users/xxx/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/javascript/node-package.js:712:16)
    at NodePackage.postSynthesize (/Users/xxx/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/javascript/node-package.js:302:18)
    at AwsCdkTypeScriptApp.synth (/Users/xxx/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/project.js:281:22)
    at evalmachine.<anonymous>:13:20
    at Script.runInContext (node:vm:139:12)
    at Object.runInContext (node:vm:289:6)
    at createProject (/Users/xxx/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/projects.js:74:8) {
  status: 127,
  signal: null,
  output: [
    null,
    null,
    <Buffer 2f 62 69 6e 2f 73 68 3a 20 79 61 72 6e 3a 20 63 6f 6d 6d 61 6e 64 20 6e 6f 74 20 66 6f 75 6e 64 0a>
  ],
  pid: 9238,
  stdout: null,
  stderr: <Buffer 2f 62 69 6e 2f 73 68 3a 20 79 61 72 6e 3a 20 63 6f 6d 6d 61 6e 64 20 6e 6f 74 20 66 6f 75 6e 64 0a>
}`

**Comment by juanledesma84** [comment]
I just install yarn, and the creation process works
