### ISSUE TITLE
nextjs-ts project with tailwindcss does not compile

### ISSUE THREAD

**Issue by mnoumanshahzad** [projen/projen#1853]
# nextjs-ts project with tailwindcss does not compile

### Toolchain versions
- node: v16.5.0
- npm: 8.10.0
- yarn: 1.22.10
- projen: 0.56.8

### Steps to reproduce error when running in development
- In a new, empty directory
- Run `projen new nextjs-ts`
- Run `npx projen dev`
- Open browser at `http://localhost:3000`
- The error pops up on the terminal running `npx projen dev`

#### Error thrown
```terminal
❯ pj dev                                                                                                               
👾 dev | next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
We detected TypeScript in your project and reconfigured your tsconfig.json file for you. Strict-mode is set to false by default.

The following suggested values were added to your tsconfig.json. These values can be changed to fit your project's needs:

	- incremental was set to true

wait  - compiling...
event - compiled client and server successfully in 1262 ms (112 modules)
wait  - compiling / (client and server)...
wait  - compiling...
error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[7].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[7].use[2]!./node_modules/tailwindcss/tailwind.css
TypeError: Cannot read property 'config' of undefined
Could not find files for / in .next/build-manifest.json
Could not find files for / in .next/build-manifest.json
wait  - compiling /_error (client and server)...
wait  - compiling...
error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[7].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[7].use[2]!./node_modules/tailwindcss/tailwind.css
TypeError: Cannot read property 'config' of undefined
    at runMicrotasks (<anonymous>)
```

### Steps to reproduce error when compiling
- In a new, empty directory
- Run `projen new nextjs-ts`
- Run `npx projen compile`

#### Error thrown
```terminal
❯ pj compile                                                                                                          
👾 compile | tsc --build
👾 compile | next build
info  - Checking validity of types
warn  - No ESLint configuration detected. Run next lint to begin setup
info  - Creating an optimized production build
Failed to compile.

./node_modules/tailwindcss/tailwind.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[7].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[7].use[2]!./node_modules/tailwindcss/tailwind.css
TypeError: Cannot read property 'config' of undefined
    at getTailwindConfig (/private/tmp/pj-nextjs-ts-fixed/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:132:62)
    at /private/tmp/pj-nextjs-ts-fixed/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:21:92
    at /private/tmp/pj-nextjs-ts-fixed/node_modules/tailwindcss/lib/processTailwindFeatures.js:38:11
    at plugins (/private/tmp/pj-nextjs-ts-fixed/node_modules/tailwindcss/lib/index.js:33:58)
    at LazyResult.runOnRoot (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/node_modules/postcss/lib/lazy-result.js:206:17)

Import trace for requested module:
./node_modules/tailwindcss/tailwind.css
./pages/index.tsx

./node_modules/tailwindcss/tailwind.css
TypeError: Cannot read property 'config' of undefined
    at getTailwindConfig (/private/tmp/pj-nextjs-ts-fixed/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:132:62)
    at /private/tmp/pj-nextjs-ts-fixed/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:21:92
    at /private/tmp/pj-nextjs-ts-fixed/node_modules/tailwindcss/lib/processTailwindFeatures.js:38:11
    at plugins (/private/tmp/pj-nextjs-ts-fixed/node_modules/tailwindcss/lib/index.js:33:58)
    at LazyResult.runOnRoot (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/node_modules/postcss/lib/lazy-result.js:206:17)
    at tryRunOrWebpackError (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:42028:9)
    at __webpack_require_module__ (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:27488:12)
    at __nested_webpack_require_153152__ (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:27445:18)
    at /private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:27516:20
    at symbolIterator (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/neo-async/async.js:1:14443)
    at done (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/neo-async/async.js:1:14823)
    at Hook.eval [as callAsync] (eval at create (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:141841:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:141643:14)
    at /private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:27423:43
    at symbolIterator (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/neo-async/async.js:1:14401)
-- inner error --
TypeError: Cannot read property 'config' of undefined
    at getTailwindConfig (/private/tmp/pj-nextjs-ts-fixed/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:132:62)
    at /private/tmp/pj-nextjs-ts-fixed/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:21:92
    at /private/tmp/pj-nextjs-ts-fixed/node_modules/tailwindcss/lib/processTailwindFeatures.js:38:11
    at plugins (/private/tmp/pj-nextjs-ts-fixed/node_modules/tailwindcss/lib/index.js:33:58)
    at LazyResult.runOnRoot (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/node_modules/postcss/lib/lazy-result.js:206:17)
    at Object.<anonymous> (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[7].use[1]!/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[7].use[2]!/private/tmp/pj-nextjs-ts-fixed/node_modules/tailwindcss/tailwind.css:1:7)
    at /private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:91471:11
    at Hook.eval [as call] (eval at create (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:141827:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:141639:14)
    at /private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:27490:39
    at tryRunOrWebpackError (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:42023:7)
    at __webpack_require_module__ (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:27488:12)
    at __nested_webpack_require_153152__ (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:27445:18)
    at /private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/webpack/bundle5.js:27516:20
    at symbolIterator (/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/compiled/neo-async/async.js:1:14443)

Generated code for /private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[7].use[1]!/private/tmp/pj-nextjs-ts-fixed/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[7].use[2]!/private/tmp/pj-nextjs-ts-fixed/node_modules/tailwindcss/tailwind.css

Import trace for requested module:
./pages/index.tsx


> Build failed because of webpack errors
👾 Task "compile" failed when executing "next build" (cwd: /private/tmp/pj-nextjs-ts-fixed)
```

**Comment by mnoumanshahzad** [comment]
Possible reasons for the behavior

- The tailwind configuration file generated is different than the default one.
  > By default, Tailwind will look for an optional `tailwind.config.js` file at the root of your project where you can define any customizations.
  [Tailwind Docs | Configuration](https://tailwindcss.com/docs/configuration)
- The non-default tailwind configuration file is not declared in the postcss configuration
  > If you’re using Tailwind as a PostCSS plugin, you will need to specify your custom configuration path in your PostCSS configuration
  [Tailwind Docs | Configuration - User a different filename](https://tailwindcss.com/docs/configuration#using-a-different-file-name)
- Tailwind configuration is missing the `content` block pointing to the source directory
  > [Tailwind Docs | Configuration - Content](https://tailwindcss.com/docs/configuration#content)

**Comment by mnoumanshahzad** [comment]
I started working on a PR to submit a fix.

**Comment by hoegertn** [comment]
@mnoumanshahzad any update on this? I hit the same error

**Comment by mbonig** [comment]
If it helps, the problem seems to be about here:
https://github.com/projen/projen/blob/main/src/web/postcss.ts#L43

To get things to compile I had to update the postcss.config.json file to contain:

```json
{
  "plugins": {
    "tailwindcss": {
      "config": "./tailwind.config.json"
    },
    "autoprefixer": {}
  }
}
```
