### ISSUE TITLE
Cannot create python.PythonProject with Poetry.

### ISSUE THREAD

**Issue by mckinnsb** [projen/projen#1863]
In a new folder, execute:

```
projen new python --poetry true
```

You will see the following error:
```
projen new python --poetry true
/Users/smckinney/.nvm/versions/node/v16.13.1/lib/node_modules/projen/lib/tasks.js:45
            throw new Error(`A task with the name ${name} already exists. To override it, call removeTask first and then create the new task.`);
            ^

Error: A task with the name install already exists. To override it, call removeTask first and then create the new task.
    at Tasks.addTask (/Users/smckinney/.nvm/versions/node/v16.13.1/lib/node_modules/projen/lib/tasks.js:45:19)
    at PythonProject.addTask (/Users/smckinney/.nvm/versions/node/v16.13.1/lib/node_modules/projen/lib/project.js:116:27)
    at new Poetry (/Users/smckinney/.nvm/versions/node/v16.13.1/lib/node_modules/projen/lib/python/poetry.js:19:36)
    at new PythonProject (/Users/smckinney/.nvm/versions/node/v16.13.1/lib/node_modules/projen/lib/python/python-project.js:76:28)
    at evalmachine.<anonymous>:1:28
    at Script.runInContext (node:vm:139:12)
    at Object.runInContext (node:vm:289:6)
    at createProject (/Users/smckinney/.nvm/versions/node/v16.13.1/lib/node_modules/projen/lib/projects.js:74:8)
    at Function.createProject (/Users/smckinney/.nvm/versions/node/v16.13.1/lib/node_modules/projen/lib/projects.js:27:9)
    at initProject (/Users/smckinney/.nvm/versions/node/v16.13.1/lib/node_modules/projen/lib/cli/cmds/new.js:241:25)
```

It looks like there's another package manager that's still being configured when the poetry option is supplied.

**Comment by mckinnsb** [comment]
Additionally, it seems like you can't configure dependencies with Poetry using `deps` or `devDeps`.

**Comment by mckinnsb** [comment]
You can work around this issue by creating a new project with the defaults, and then disable venv, virtualenv, and setuptools, and enable poetry, but the dependencies still do not install. My guess is somehow poetry is getting lost in the chain.

**Comment by mckinnsb** [comment]
I did some digging - it seems like the project adds the dependencies correctly, but when the `pyproject.toml` file is being synthesized, the dependencies are lost in the resolution process.

It looks like they are being correctly returned by the synthesize functions in `PoetryProject`.

Also, it seems the error w/ creating a Project w/ Poetry might be due to the fact that the poetry option does not invalidate other options; with defaults, `--poetry true` will also set `--pip true`, which causes this particular error, but also `--venv true`, which you probably wouldn't want either.

**Comment by mrgrain** [comment]
`projen new python --poetry` works like a charm now! Thanks @mikejgray 🥳
