### ISSUE TITLE
SyntaxError when trying to create a new project

### ISSUE THREAD

**Issue by orsenthil** [projen/projen#1965]
```
node --version
v12.22.12
```

Installed projen

```
npm i -g projen
/usr/local/bin/projen -> /usr/local/lib/node_modules/projen/bin/projen
npm WARN notsup Unsupported engine for projen@0.58.21: wanted: {"node":">= 14.0.0"} (current: {"node":"12.22.12","npm":"6.14.16"})
npm WARN notsup Not compatible with your version of node/npm: projen@0.58.21

+ projen@0.58.21
updated 65 packages in 3.503s
```

### tried to setup a new project

```
$ projen new python
/usr/local/lib/node_modules/projen/lib/task-runtime.js:31
        return Object.values(this.manifest.tasks ?? {});
                                                  ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/projen/lib/cli/index.js:7:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

## Using npx

```
$ npx projen new python
Unexpected token '?'
```

**Comment by marciocadev** [comment]
This is strange behavior

Apparently `projen` is not able to create the tasks, I tried here and it worked.

I don't know if this is the problem, but I think `projen` needs node version 14 or higher

**Comment by cgatt** [comment]
Node supports the [nullish coalescing operator (??)](https://github.com/tc39/proposal-nullish-coalescing) as of Node 14.5 (see https://node.green/). Update to >= Node 14 to use Projen.

**Comment by yuth** [comment]
Projen requires node >=14. Closing the issue
