### ISSUE TITLE
[Bug] New jsii project defaulting to yarn without option for using npm

### ISSUE THREAD

**Issue by HenrikStanley** [projen/projen#2041]
When running a create for a new jsii project, the template has hardcoded a run of yarn install.
Since I do not use nor have installed yarn on my setup this fails as shown below.

There does not seem to be any options in `npx projen new jsii  --help` related to this behavior that can be set to overwrite it to use npm or pnpm instead of yarn.

```shell
npx projen new jsii 
👾 Project definition file was created at /home/vscode/projects/projen-test/.projenrc.js
node:child_process:902
    throw err;
    ^

Error: Command failed: yarn install --check-files
/bin/sh: line 1: yarn: command not found

    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at Object.exec (/home/vscode/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/util.js:15:19)
    at NodePackage.installDependencies (/home/vscode/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/javascript/node-package.js:735:16)
    at NodePackage.postSynthesize (/home/vscode/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/javascript/node-package.js:317:18)
    at JsiiProject.synth (/home/vscode/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/project.js:313:22)
    at evalmachine.<anonymous>:15:19
    at Script.runInContext (node:vm:139:12)
    at Object.runInContext (node:vm:289:6) {
  status: 127,
  signal: null,
  output: [
    null,
    null,
    <Buffer 2f 62 69 6e 2f 73 68 3a 20 6c 69 6e 65 20 31 3a 20 79 61 72 6e 3a 20 63 6f 6d 6d 61 6e 64 20 6e 6f 74 20 66 6f 75 6e 64 0a>
  ],
  pid: 892,
  stdout: null,
  stderr: <Buffer 2f 62 69 6e 2f 73 68 3a 20 6c 69 6e 65 20 31 3a 20 79 61 72 6e 3a 20 63 6f 6d 6d 61 6e 64 20 6e 6f 74 20 66 6f 75 6e 64 0a>
}
```

**Comment by HenrikStanley** [comment]
I am an idiot and somehow missed the `--package-manager` flag
