### ISSUE TITLE
Incompatibility with yarn stable

### ISSUE THREAD

**Issue by kcolemangt** [projen/projen#2285]
#### Steps to reproduce the issue

1. 
``` 
% yarn set version stable
warning package.json: No license field
➤ YN0000: Retrieving https://repo.yarnpkg.com/3.3.0/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.3.0.cjs
➤ YN0000: Done in 0s 333ms
% yarn --version
3.3.0
```
2. 
```
 % projen --version
0.65.50
```
3. 
```
% projen new awscdk-app-ts   
👾 Project definition file was created at /usr/local/src/cdk/.projenrc.js
Unknown Syntax Error: Unsupported option name ("--check-files").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
node:child_process:946
    throw err;
    ^

Error: Command failed: yarn install --check-files
    at checkExecSyncError (node:child_process:871:11)
    at Object.execSync (node:child_process:943:15)
    at Object.exec (/Users/local/.nvm/versions/node/v18.12.1/lib/node_modules/projen/lib/util.js:15:19)
    at NodePackage.installDependencies (/Users/local/.nvm/versions/node/v18.12.1/lib/node_modules/projen/lib/javascript/node-package.js:766:16)
    at NodePackage.postSynthesize (/Users/local/.nvm/versions/node/v18.12.1/lib/node_modules/projen/lib/javascript/node-package.js:336:18)
    at AwsCdkTypeScriptApp.synth (/Users/local/.nvm/versions/node/v18.12.1/lib/node_modules/projen/lib/project.js:313:22)
    at evalmachine.<anonymous>:13:20
    at Script.runInContext (node:vm:141:12)
    at Object.runInContext (node:vm:297:6) {
  status: 1,
  signal: null,
  output: [ null, null, <Buffer > ],
  pid: 51658,
  stdout: null,
  stderr: <Buffer >
}
```

#### What's the expected result?

- Install the awscdk-app-ts project

#### What's the actual result?

- Failure to install

#### Additional details / screenshot

Switching to Yarn "classic" allows projen to function.

1. 
```
% yarn set version classic
➤ YN0000: Retrieving https://classic.yarnpkg.com/latest.js
➤ YN0000: Saving the new release in ../.yarn/releases/yarn-1.22.19.cjs
➤ YN0000: Done in 0s 611ms
% yarn --version          
1.22.19
```
2. 
```
% projen new awscdk-app-ts    
👾 Project definition file was created at /usr/local/src/cdk/.projenrc.js
yarn install v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 17.77s.
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 2.73s.

> cdk@0.0.0 eslint
> npx projen eslint

Initialized empty Git repository in /usr/local/src/cdk/.git/
[main (root-commit) 7b71356] chore: project created with projen
 22 files changed, 6636 insertions(+)
 create mode 100644 .eslintrc.json
 create mode 100644 .gitattributes
 create mode 100644 .github/pull_request_template.md
 create mode 100644 .github/workflows/build.yml
 create mode 100644 .github/workflows/pull-request-lint.yml
 create mode 100644 .github/workflows/upgrade.yml
 create mode 100644 .gitignore
 create mode 100644 .mergify.yml
 create mode 100644 .npmignore
 create mode 100644 .projen/deps.json
 create mode 100644 .projen/files.json
 create mode 100644 .projen/tasks.json
 create mode 100644 .projenrc.js
 create mode 100644 LICENSE
 create mode 100644 README.md
 create mode 100644 cdk.json
 create mode 100644 package.json
 create mode 100644 src/main.ts
 create mode 100644 test/main.test.ts
 create mode 100644 tsconfig.dev.json
 create mode 100644 tsconfig.json
 create mode 100644 yarn.lock
 ```

**Comment by agdimech** [comment]
The issue appears to be that the [install command ](https://github.com/projen/projen/blob/main/src/javascript/node-package.ts#L1049)that projen uses only supports yarn 1.x.

I see two potential solutions:

**Solution 1: Add a new enum value to [NodePackageManager]**(https://github.com/projen/projen/blob/main/src/javascript/node-package.ts#L1424) called `YARN2` and return `yarn install ${frozen ? '--immutable' : ''}` from the [renderInstallCommand](https://github.com/projen/projen/blob/main/src/javascript/node-package.ts#L1045).

**Solution 2: Check version of yarn used**
When performing logic that checks if the packageManager is set to yarn, we additionally check to see if the version is >= 2. If so we conditionally return commands using yarn 2+ syntax.

**Comment by mrgrain** [comment]
Thanks @agdimech ! I reckon a new `YARN2` type is what's needed here.

> Solution 2: Check version of yarn used

Not sure if or where projen is doing this already. 'd be surprised though if we currently do this check every time projen runs.
For example tasks are stored in `.projen/tasks.json` and that would currently include the wrong lockfile option.

**Comment by agdimech** [comment]
@mrgrain - I added a PR which adds support for YARN2. Has not been tested.
