### ISSUE TITLE
synthSnapshot is broken

### ISSUE THREAD

**Issue by AminFazlMondo** [projen/projen#2286]
Upgrading to the latest version of projen has broken tests for [my JSII project](https://github.com/AminFazlMondo/Lerna-Projen/pull/314), it seems to not be able to parse some of non json files (eg, gitignore, etc)

I think this has been introduced by merging #2260 

```
fileName: .gitignore

error:
SyntaxError: Unexpected token # in JSON at position 0
        at JSON.parse (<anonymous>)
        at directorySnapshot (/home/amin/Develop/Lerna-Projen/node_modules/projen/src/util/synth.ts:122:13)
        at synthSnapshot (/home/amin/Develop/Lerna-Projen/node_modules/projen/src/util/synth.ts:57:12)
        at /home/amin/Develop/Lerna-Projen/test/index.test.ts:118:31
        at _dispatchDescribe (/home/amin/Develop/Lerna-Projen/node_modules/jest-circus/build/index.js:98:26)
        at describe (/home/amin/Develop/Lerna-Projen/node_modules/jest-circus/build/index.js:60:5)
        at Object.<anonymous> (/home/amin/Develop/Lerna-Projen/test/index.test.ts:116:1)
        at Runtime._execModule (/home/amin/Develop/Lerna-Projen/node_modules/jest-runtime/build/index.js:1646:24)
        at Runtime._loadModule (/home/amin/Develop/Lerna-Projen/node_modules/jest-runtime/build/index.js:1185:12)
        at Runtime.requireModule (/home/amin/Develop/Lerna-Projen/node_modules/jest-runtime/build/index.js:1009:12)
```

**Comment by mrgrain** [comment]
Ah yes, I know why. The `synthSnapshot` helper decides which parser library should be used based on the internal file list projen maintains. `directorySnapshot` then goes on to snapshot all files, including the ones on subprojects that it doesn't  know about.

Fix should be to just always use the comment-json library to parse json files.
