### ISSUE TITLE
Cannot init a new React project with Typescript

### ISSUE THREAD

**Issue by 70nyIT** [projen/projen#2448]
After issue https://github.com/projen/projen/issues/2443 have been fixed (and now the problem is no more present), I tried to init a new React project with TypeScript.

Steps I made:
* created a new empty repository
* cloned locally and entered in the folder
* run the command `npx projen new --from react-ts`

It asks me to install `projen` (I accept) and it installs version `0.67.55`. But then when it starts installing packages for the react App, it crashes with this stacktrace

```
Error: Command failed: npm install --save-dev -f --no-package-lock --prefix="/home/myUser/job repos/test" react-ts
npm WARN using --force Recommended protections disabled.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated acorn-dynamic-import@2.0.2: This is probably built in to whatever tool you're using. If you still need it... idk
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated extract-text-webpack-plugin@2.1.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN deprecated html-webpack-plugin@2.30.1: out of support
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated svgo@0.7.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /home/myUser/job repos/test/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/bin/node /home/myUser/job repos/test/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/home/myUser/job repos/test/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.15.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/myUser/job repos/test/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/myUser/job repos/test/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/myUser/job repos/test/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/myUser/job repos/test/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/myUser/job repos/test/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/myUser/job repos/test/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/myUser/job repos/test/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/myUser/job repos/test/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/myUser/job repos/test/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/myUser/job repos/test/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/myUser/job repos/test/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/myUser/job repos/test/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/myUser/job repos/test/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/myUser/job repos/test/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/myUser/job repos/test/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/myUser/job repos/test/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/myUser/job repos/test/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/myUser/job repos/test/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/myUser/job repos/test/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/myUser/job repos/test/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/myUser/job repos/test/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/myUser/job repos/test/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/myUser/job repos/test/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/myUser/job repos/test/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/home/myUser/job repos/test/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/home/myUser/job repos/test/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/home/myUser/job repos/test/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/home/myUser/job repos/test/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /home/myUser/job repos/test/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /home/myUser/job repos/test/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/myUser/job repos/test/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Linux 5.14.0-1051-oem
npm ERR! gyp ERR! command "/usr/local/bin/node" "/home/myUser/job repos/test/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/myUser/job repos/test/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.15.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myUser/.npm/_logs/2023-02-15T08_53_07_805Z-debug-0.log

    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at Object.exec (/home/myUser/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/util.js:15:19)
    at Object.installPackage (/home/myUser/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/util.js:21:12)
    at initProjectFromModule (/home/myUser/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js:197:31)
    at Object.handler (/home/myUser/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js:101:20)
    at Object.runCommand (/home/myUser/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:446:48)
    at Object.parseArgs [as _parseArgs] (/home/myUser/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:2697:57)
    at Function.get [as argv] (/home/myUser/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:2651:25) {
  status: 1,
  signal: null,
  output: [
    null,
    null,
    <Buffer 6e 70 6d 20 57 41 52 4e 20 75 73 69 6e 67 20 2d 2d 66 6f 72 63 65 20 52 65 63 6f 6d 6d 65 6e 64 65 64 20 70 72 6f 74 65 63 74 69 6f 6e 73 20 64 69 73 ... 98494 more bytes>
  ],
  pid: 52715,
  stdout: null,
  stderr: <Buffer 6e 70 6d 20 57 41 52 4e 20 75 73 69 6e 67 20 2d 2d 66 6f 72 63 65 20 52 65 63 6f 6d 6d 65 6e 64 65 64 20 70 72 6f 74 65 63 74 69 6f 6e 73 20 64 69 73 ... 98494 more bytes>
}
``` 

If I can help with further logs or details, please let me know.

**Comment by 70nyIT** [comment]
Looks like it's searching for `python2` for what I can understand. I have only `python3` (and the `python` alias points to `python3`). I'd prefer not to have `python2` installed. Currently using `Ubuntu 22.04.1 LTS`

**Comment by mrgrain** [comment]
It also checks for `python`:
```
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
```
Aliases are shell specific and usually do not not work for this.

Either way, we won't be able to change how `node-gyp` works. =/
But looks like you can configure it to some extent: https://github.com/nodejs/node-gyp#configuring-python-dependency
