### ISSUE TITLE
setting --extra-index-url in requirements text for python project is not possibel

### ISSUE THREAD

**Issue by anux-linux** [projen/projen#2464]
I have some libraries which are hosted in a private PIP repository. Usually I can set the requirements.txt with the --extra-index-url with a specific token to make pip query this repository and install the dependency. 

Since the requirments.txt is generated by projen, I need to set the --extra-index-url in the .pronjenrc. I did not found a extra parameter to set this value and adding the url to the DEV list throws this error: 

`
/dev/projen/python/test/node_modules/projen/node_modules/semver/classes/comparator.js:38
      throw new TypeError('Invalid comparator: ${comp}')   
             `
`TypeError: Invalid comparator: gitlab.com/api/v4/projects/468654/packages/pypi/simple
    at Comparator.parse (/dev/projen/python/test/node_modules/projen/node_modules/semver/classes/comparator.js:38:13)
    at new Comparator (/dev/projen/python/test/node_modules/projen/node_modules/semver/classes/comparator.js:22:10)
    at /dev/projen/python/test/node_modules/projen/node_modules/semver/classes/range.js:133:47
    at Array.map (<anonymous>)
    at Range.parseRange (/dev/projen/python/test/node_modules/projen/node_modules/semver/classes/range.js:133:35)
    at /dev/projen/python/test/node_modules/projen/node_modules/semver/classes/range.js:34:22
    at Array.map (<anonymous>)
    at new Range (/dev/projen/python/test/node_modules/projen/node_modules/semver/classes/range.js:34:8)
    at Object.toPythonVersionRange (/dev/projen/python/test/node_modules/projen/src/util/semver.ts:53:17)
    at RequirementsFile.formatDependency (/dev/projen/python/test/node_modules/projen/src/python/requirements-file.ts:57:28)
`

**Comment by anux-linux** [comment]
the entry should look like this: 

`--extra-index-url=https://__token__:{MY_TOKEN}@gitlab.com/api/v4/projects/8722447/packages/pypi/simple`

Generation of the requirements.txt fails because of the _@_ symbol in the URL

**Comment by mrgrain** [comment]
Gotcha. Thank you. I don't think adding `--extra-index-url` as a dependency would be a good interface. We probably want some sort of support for adding other supported values.

**Comment by AljoSt** [comment]
Any update on this? having a similar problem when adding github source (git+ssh://git@github.com/my_org/my_repo.git@v1.0.0#egg=my_package)
