### ISSUE TITLE
Projen new throws RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by richarddowner** [projen/projen#2574]
Hello, first time trying to run `npx projen new awscdk-construct` and am getting this error:

```
npx projen new awscdk-construct
RangeError: Maximum call stack size exceeded
    at existsSync (node:fs:301:20)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:84:29)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
```

Versions:
- npm: 9.6.3
- npx: 9.6.3
- node: v18.15.0

Things already tried:
- Re-installing Node/npm
- Updating Node/npm
- Clearing node caches etc
- Searched for similar problem in Issues section
- Can find similar problems online but not relating to projen. Solutions seem to be around user written code with recursion problems.

Thank you.

**Comment by richarddowner** [comment]
Thank you @mrgrain for looking into this so fast!
