### ISSUE TITLE
projen 0.70.6 and eslint strange error

### ISSUE THREAD

**Issue by anh-rivergon** [projen/projen#2579]
The error is only for the first import. It says "Parsing error: Cannot read file "/home/usera/workspace/projecta/tsconfig.dev.json'.eslint"

the actual directory of the projen project is "/home/usera/workspace/projecta/amazon-aws/projecta-cdk/projecta-stacks" and there is a tsconfig.dev.json in "/home/usera/workspace/projecta/amazon-aws/projecta-cdk/projecta-stacks"

Strange...anyone got an idea?

<img width="248" alt="image" src="https://user-images.githubusercontent.com/70559415/229333891-a7383348-7239-46cd-b00f-1c60b0f9b7e6.png">

**Comment by anh-rivergon** [comment]
Also got the following eslint error

warning " > ts-jest@27.1.5" has incorrect peer dependency "typescript@>=3.8 <5.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 31.88s.
👾 Installing dependencies...
👾 install | yarn install --check-files
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > ts-jest@27.1.5" has incorrect peer dependency "typescript@>=3.8 <5.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 7.96s.

> xyzbet-platform-dev-sandbox-stacks@0.0.0 eslint
> npx projen eslint


/home/abc/workspace/projecta/amazon-aws/xyzbet-platform-amazon-aws-cdk/xyzbet-platform-dev-sandbox-stacks/src/index.ts
  1:99  error  Unable to resolve path to module '@oneb-amazon-aws-cdk/customer-identity-aws-access-cognito-construct'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)

Error: Command failed: npm run eslint --if-present
👾 eslint | eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test build-tools .projenrc.js
👾 Task "eslint" failed when executing "eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test build-tools .projenrc.js" (cwd: /home/abc/workspace/projecta/amazon-aws/xyzbet-platform-amazon-aws-cdk/xyzbet-platform-dev-sandbox-stacks)

    at checkExecSyncError (node:child_process:861:11)
    at Object.execSync (node:child_process:932:15)
    at exec (/home/abc/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/util.js:15:19)
    at initProject (/home/abc/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js:289:25)
    at Object.handler (/home/abc/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js:92:36)
    at Object.runCommand (/home/abc/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:446:48)
    at Object.parseArgs [as _parseArgs] (/home/abc/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:2697:57)
    at Object.runCommand (/home/abc/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:410:36)
    at Object.parseArgs [as _parseArgs] (/home/abc/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:2697:57) {
  status: 1,
  signal: null,
  output: [
    null,
    null,
    <Buffer f0 9f 91 be 20 1b 5b 33 37 6d 1b 5b 34 6d 65 73 6c 69 6e 74 1b 5b 32 34 6d 20 7c 20 65 73 6c 69 6e 74 20 2d 2d 65 78 74 20 2e 74 73 2c 2e 74 73 78 20 ... 339 more bytes>
  ],
  pid: 22476,
  stdout: null,
  stderr: <Buffer f0 9f 91 be 20 1b 5b 33 37 6d 1b 5b 34 6d 65 73 6c 69 6e 74 1b 5b 32 34 6d 20 7c 20 65 73 6c 69 6e 74 20 2d 2d 65 78 74 20 2e 74 73 2c 2e 74 73 78 20 ... 339 more bytes>
}

**Comment by mrgrain** [comment]
It's this a newly created project? What's the project type you are using?

Saying that, there's a bit of a chicken-egg situation when new TS versions are released. But default projen will pick the latest TS version, but `ts-jest` typically doesn't support them until a month or so after. We don't have a good way of establishing that relationship yet unfortunately.

I'd recommend you downgrade to TS4.9 for now.

**Comment by mrgrain** [comment]
> The error is only for the first import. It says "Parsing error: Cannot read file "/home/usera/workspace/projecta/tsconfig.dev.json'.eslint"
> 
> the actual directory of the projen project is "/home/usera/workspace/projecta/amazon-aws/projecta-cdk/projecta-stacks" and there is a tsconfig.dev.json in "/home/usera/workspace/projecta/amazon-aws/projecta-cdk/projecta-stacks"
> 
> Strange...anyone got an idea?
> 
> <img width="248" alt="image" src="https://user-images.githubusercontent.com/70559415/229333891-a7383348-7239-46cd-b00f-1c60b0f9b7e6.png">
> 

Regarding this error, it sounds like the eslint  config somehow places the project root into a different location (`/home/usera/workspace/projecta/`) then where it should be. Is this by any chance a "nested" project? As in, is there any reason eslint could believe `projecta` is the root? For example does it have a .git directory, package.json file or eslint.config.json file?

**Comment by anh-rivergon** [comment]
About the issue - I am moving the other observation about eslint to a new issue to avoid confusion.

_The error is only for the first import. It says "Parsing error: Cannot read file "/home/usera/workspace/projecta/tsconfig.dev.json'.eslint"_

Brand-new awscdk-construct project.  Here is what I found:

1. I use Windows and WSL2, Ubuntu 20
2. From Visual Studio code, after connecting to WSL and opening a folder workspace which contains the projen project (brand-new), I get the eslint error
3. From Visual Studio code, after connecting to WSL and opening the folder workspace/projecta (the projen project folder itself), I do not get the eslint error. The root is projecta itself.

So, yeah, it would seem eslint is search upward to the parent folders. 

The .eslintrc.json is supplied below.

// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
{
  "env": {
    "jest": true,
    "node": true
  },
  "root": true,
  "plugins": [
    "@typescript-eslint",
    "import"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
    "project": "./tsconfig.dev.json"
  },
  "extends": [
    "plugin:import/typescript"
  ],
  "settings": {
    "import/parsers": {
      "@typescript-eslint/parser": [
        ".ts",
        ".tsx"
      ]
    },
    "import/resolver": {
      "node": {},
      "typescript": {
        "project": "./tsconfig.dev.json",
        "alwaysTryTypes": true
      }
    }
  },
  "ignorePatterns": [
    "*.js",
    "*.d.ts",
    "node_modules/",
    "*.generated.ts",
    "coverage",
    "!.projenrc.js"
  ],
  "rules": {
    "indent": [
      "off"
    ],
    "@typescript-eslint/indent": [
      "error",
      2
    ],
    "quotes": [
      "error",
      "single",
      {
        "avoidEscape": true
      }
    ],
    "comma-dangle": [
      "error",
      "always-multiline"
    ],
    "comma-spacing": [
      "error",
      {
        "before": false,
        "after": true
      }
    ],
    "no-multi-spaces": [
      "error",
      {
        "ignoreEOLComments": false
      }
    ],
    "array-bracket-spacing": [
      "error",
      "never"
    ],
    "array-bracket-newline": [
      "error",
      "consistent"
    ],
    "object-curly-spacing": [
      "error",
      "always"
    ],
    "object-curly-newline": [
      "error",
      {
        "multiline": true,
        "consistent": true
      }
    ],
    "object-property-newline": [
      "error",
      {
        "allowAllPropertiesOnSameLine": true
      }
    ],
    "keyword-spacing": [
      "error"
    ],
    "brace-style": [
      "error",
      "1tbs",
      {
        "allowSingleLine": true
      }
    ],
    "space-before-blocks": [
      "error"
    ],
    "curly": [
      "error",
      "multi-line",
      "consistent"
    ],
    "@typescript-eslint/member-delimiter-style": [
      "error"
    ],
    "semi": [
      "error",
      "always"
    ],
    "max-len": [
      "error",
      {
        "code": 150,
        "ignoreUrls": true,
        "ignoreStrings": true,
        "ignoreTemplateLiterals": true,
        "ignoreComments": true,
        "ignoreRegExpLiterals": true
      }
    ],
    "quote-props": [
      "error",
      "consistent-as-needed"
    ],
    "@typescript-eslint/no-require-imports": [
      "error"
    ],
    "import/no-extraneous-dependencies": [
      "error",
      {
        "devDependencies": [
          "**/test/**",
          "**/build-tools/**"
        ],
        "optionalDependencies": false,
        "peerDependencies": true
      }
    ],
    "import/no-unresolved": [
      "error"
    ],
    "import/order": [
      "warn",
      {
        "groups": [
          "builtin",
          "external"
        ],
        "alphabetize": {
          "order": "asc",
          "caseInsensitive": true
        }
      }
    ],
    "no-duplicate-imports": [
      "error"
    ],
    "no-shadow": [
      "off"
    ],
    "@typescript-eslint/no-shadow": [
      "error"
    ],
    "key-spacing": [
      "error"
    ],
    "no-multiple-empty-lines": [
      "error"
    ],
    "@typescript-eslint/no-floating-promises": [
      "error"
    ],
    "no-return-await": [
      "off"
    ],
    "@typescript-eslint/return-await": [
      "error"
    ],
    "no-trailing-spaces": [
      "error"
    ],
    "dot-notation": [
      "error"
    ],
    "no-bitwise": [
      "error"
    ],
    "@typescript-eslint/member-ordering": [
      "error",
      {
        "default": [
          "public-static-field",
          "public-static-method",
          "protected-static-field",
          "protected-static-method",
          "private-static-field",
          "private-static-method",
          "field",
          "constructor",
          "method"
        ]
      }
    ]
  },
  "overrides": [
    {
      "files": [
        ".projenrc.js"
      ],
      "rules": {
        "@typescript-eslint/no-require-imports": "off",
        "import/no-extraneous-dependencies": "off"
      }
    }
  ]
}

**Comment by anh-rivergon** [comment]
Well, I guaranteed it is opened properly from WSL and not from Windows :)
I figure Visual Studio + WSL + projen is one real popular combination and curious if anyone has encountered this and/or has a fix?

**Comment by mrgrain** [comment]
Are you using `nx-monorepo`?

Because I hit a similar issue today as well while using that.
