### ISSUE TITLE
bug(javascript): npmconfig broken as part of v0.71.27

### ISSUE THREAD

**Issue by gradybarrett** [projen/projen#2635]
It appears that [v0.71.27](https://github.com/projen/projen/releases/tag/v0.71.27) broke NpmConfig with the following error:

`Error: there is already a file under .npmrc`

Relevant projenrc.ts line:

```typescript
new javascript.NpmConfig(project, { registry: privateRegistryUrl });
```

Stacktrace:
```text
/Users/n0237835/code/innersource/swa/swa-cdk-authorizers/node_modules/projen/src/file.ts:110
      throw new Error(
            ^
Error: there is already a file under .npmrc
    at new FileBase (/Users/n0237835/code/innersource/swa/swa-cdk-authorizers/node_modules/projen/src/file.ts:110:13)
    at new ObjectFile (/Users/n0237835/code/innersource/swa/swa-cdk-authorizers/node_modules/projen/src/object-file.ts:51:5)
    at new IniFile (/Users/n0237835/code/innersource/swa/swa-cdk-authorizers/node_modules/projen/src/ini.ts:16:5)
    at new NpmConfig (/Users/n0237835/code/innersource/swa/swa-cdk-authorizers/node_modules/projen/src/javascript/npm-config.ts:38:5)
    at Object.<anonymous> (/Users/n0237835/code/innersource/swa/swa-cdk-authorizers/.projenrc.ts:132:1)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Module.m._compile (/Users/n0237835/code/innersource/swa/swa-cdk-authorizers/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/n0237835/code/innersource/swa/swa-cdk-authorizers/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
```

I haven't had a chance to reproduce in a simpler project. I only got as far as isolating it to >= v0.71.27.

**Comment by mrgrain** [comment]
You can use `javascript.npmrc` instead to add your configuration.

**Comment by gradybarrett** [comment]
Ahh thanks @mrgrain. I didn't quite get to looking at that 0.7.27 pull request so missed the new interface.

**Comment by mrgrain** [comment]
No worries, thanks for reporting it anyway!
