### ISSUE TITLE
Upgrade from 0.71.26 to 0.71.28 breaks .npmrc

### ISSUE THREAD

**Issue by bruecktech** [projen/projen#2638]
I updated from 0.71.26 to 0.71.28 and now this code breaks

```
export class MyCdkTypeScriptApp extends awscdk.AwsCdkTypeScriptApp {
    constructor(options: MyCdkTypeScriptAppOptions) {
        super(options);
        const npmrc = new NpmConfig(this);
        npmrc.addRegistry('https://foobar.com/repository/npm/', '@cdk');
    }
}
```

Error:
```
❯ yarn projen
yarn run v1.22.19
$ npx projen
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
/Users/foo/mycdktypescriptapp/node_modules/projen/src/file.ts:110
      throw new Error(
            ^
Error: there is already a file under .npmrc
    at new FileBase (/Users/foo/mycdktypescriptapp/node_modules/projen/src/file.ts:110:13)
    at new ObjectFile (/Users/foo/mycdktypescriptapp/node_modules/projen/src/object-file.ts:51:5)
    at new IniFile (/Users/foo/mycdktypescriptapp/node_modules/projen/src/ini.ts:16:5)
    at new NpmConfig (/Users/foo/mycdktypescriptapp/node_modules/projen/src/javascript/npm-config.ts:38:5)
    at new MyCdkTypeScriptApp (/Users/foo/mycdktypescriptapp/node_modules/@cdk/foo-cdk-projen/src/projen/cdk-typescript-app.ts:100:27)
    at Object.<anonymous> (/Users/foo/mycdktypescriptapp/.projenrc.ts:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/Users/foo/mycdktypescriptapp/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/foo/mycdktypescriptapp/node_modules/ts-node/src/index.ts:1621:12)
👾 Synthesis failed: Task "default" failed when executing "ts-node --project tsconfig.dev.json .projenrc.ts" (cwd: /Users/foo/mycdktypescriptapp)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

There is no existing `.npmrc` in the project
Reverting back to 0.71.26 solves the issue.

**Comment by mrgrain** [comment]
The API has changed. You can now use `project.npmrc` to access the configuration.

Same as https://github.com/projen/projen/issues/2635

**Comment by bruecktech** [comment]
Thanks, I wasn't aware of it. It works now. Sorry for the noise.
