### ISSUE TITLE
Error while publishing AwsCdkConstructLibrary

### ISSUE THREAD

**Issue by helloworld121** [projen/projen#2738]
Hi,
this issue is related is the ticket I created earlier:
https://github.com/projen/projen/issues/2733

After creating a new project by running: 
npx projen new awscdk-construct

I wanted to publish it using a build-pipeline (gitlab). Therefore I created a new pipeline in the new created project, and
1) install dependencies
2) build project by running "npx projen build"
But the build step failed with the output I added below.

```
$ npx projen build
👾 build » default | ts-node --project tsconfig.dev.json .projenrc.ts
👾 build » compile | jsii --silence-warnings=reserved-word
👾 build » post-compile » docgen | jsii-docgen -o API.md
-
- You are currently using jsii-rosetta@1.x. We recommend upgrading to jsii-rosetta@5.0.x or       ---
- later. This will allow you to use modern TypeScript syntax, and improves compatibility with     -
- many common dependencies. For example, recent versions of @types/node.                          -
-                                                                                                 -
- 5.0.x and subsequent releases of jsii-rosetta use the same major.minor version as the           -
- TypeScript compiler they are built on. We recommend declaring a minor-pinned (also known as     -
- "tilde") dependency on jsii-rosetta (e.g: `"jsii-rosetta": "5.0.x"` or                          -
- `"jsii-rosetta": "~5.0.7"`).                                                                    -
-                                                                                                 -
- For more information, see: https://aws.github.io/jsii/compiler-and-rosetta-maintenance/         -
-                                                                                                 -
- This warning can be suppressed by setting the JSII_SUPPRESS_UPGRADE_PROMPT environment variable -
-
👾 build » test | jest --passWithNoTests --updateSnapshot
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
....
Ran all test suites.
👾 build » test » eslint | eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test build-tools projenrc .projenrc.ts
👾 build » package | if [ ! -z ${CI} ]; then rsync -a . .repo --exclude .git --exclude node_modules && rm -rf dist && mv .repo dist; else npx projen package-all; fi
/bin/sh: rsync: not found
👾 Task "build » package" failed when executing "if [ ! -z ${CI} ]; then rsync -a . .repo --exclude .git --exclude node_modules && rm -rf dist && mv .repo dist; else npx projen package-all; fi" (cwd: /builds/test-next)
```

I am not sure if this is related, to the file ".jsii", that is part of ".gitignore".
If I run the build locally I get the following error:

```
$ npm run build

> test-next@0.0.0 build
> npx projen build

� build » default | ts-node --project tsconfig.dev.json .projenrc.ts
� Installing dependencies...
� install | npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: jest-config@29.5.0
npm WARN Found: @types/node@20.3.1
npm WARN node_modules/jest-config/node_modules/@types/node
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional @types/node@"*" from jest-config@29.5.0
npm WARN node_modules/jest-config
npm WARN   jest-config@"^29.5.0" from @jest/core@29.5.0
npm WARN   node_modules/@jest/core
npm WARN   1 more (jest-cli)

up to date, audited 1021 packages in 2s

188 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
� build » compile | jsii --silence-warnings=reserved-word
� build » post-compile » docgen | jsii-docgen -o API.md
-
- You are currently using jsii-rosetta@1.x. We recommend upgrading to jsii-rosetta@5.0.x or       -
- later. This will allow you to use modern TypeScript syntax, and improves compatibility with     -
- many common dependencies. For example, recent versions of @types/node.                          -
-                                                                                                 -
- 5.0.x and subsequent releases of jsii-rosetta use the same major.minor version as the           -
- TypeScript compiler they are built on. We recommend declaring a minor-pinned (also known as     -
- "tilde") dependency on jsii-rosetta (e.g: `"jsii-rosetta": "5.0.x"` or                          -
- `"jsii-rosetta": "~5.0.7"`).                                                                    -
-                                                                                                 -
- For more information, see: https://aws.github.io/jsii/compiler-and-rosetta-maintenance/         -
-                                                                                                 -
- This warning can be suppressed by setting the JSII_SUPPRESS_UPGRADE_PROMPT environment variable -
-
Error: Assembly "test-next" not found
    at TypeSystem.findAssembly (C:\tmp\test-next\node_modules\jsii-reflect\lib\type-system.js:147:19)
    at C:\tmp\test-next\node_modules\jsii-docgen\lib\docgen\view\documentation.js:251:23
    at async withTempDir (C:\tmp\test-next\node_modules\jsii-docgen\lib\docgen\view\documentation.js:317:16)
    at async Documentation.createAssembly (C:\tmp\test-next\node_modules\jsii-docgen\lib\docgen\view\documentation.js:228:25)
    at async Documentation.toJson (C:\tmp\test-next\node_modules\jsii-docgen\lib\docgen\view\documentation.js:140:28)
    at async Documentation.toMarkdown (C:\tmp\test-next\node_modules\jsii-docgen\lib\docgen\view\documentation.js:185:23)
    at async generateForLanguage (C:\tmp\test-next\node_modules\jsii-docgen\lib\cli.js:60:25)
    at async main (C:\tmp\test-next\node_modules\jsii-docgen\lib\cli.js:94:9)
```

Thank you for any help :)

**Comment by mrgrain** [comment]
This is the error:
```
/bin/sh: rsync: not found
```

The `package` task (which is called as part of `build`) assumes that `rsync` is available on the machine when in `CI` mode.
This is bad by projen, but that's how it is.

Either install rsync, set `CI=0` or patch your package task.

**Comment by helloworld121** [comment]
Hi @mrgrain,
thank you for your help. 
I guess all people in our company work with windows and projen doesn't seem to be as simple to use as I hoped it is. 
Therefore we will stick with basic cdk and jsii. Even though the promise of projen sounds very promissing.

**Comment by mrgrain** [comment]
Thanks for the feedback. I can understand your decision. We should document the lack of proper windows support better.

**Comment by mrgrain** [comment]
Fixed
