### ISSUE TITLE
Error: Cannot find module 'wrap-ansi'

### ISSUE THREAD

**Issue by ahammond** [projen/projen#2780]
For hysterical reasons I had to clobber / re-create my `yarn.lock` file for a cdk app. When I go to regenerate it, I see the following issue in CI failing build:

```
Error: Cannot find module 'wrap-ansi'
Require stack:
- /home/runner/work/infratest-service-cdk/infratest-service-cdk/node_modules/cliui/build/index.cjs
- /home/runner/work/infratest-service-cdk/infratest-service-cdk/node_modules/yargs/build/index.cjs
- /home/runner/work/infratest-service-cdk/infratest-service-cdk/node_modules/yargs/index.cjs
- /home/runner/work/infratest-service-cdk/infratest-service-cdk/node_modules/jest-cli/build/cli/index.js
- /home/runner/work/infratest-service-cdk/infratest-service-cdk/node_modules/jest-cli/build/index.js
- /home/runner/work/infratest-service-cdk/infratest-service-cdk/node_modules/jest-cli/bin/jest.js
- /home/runner/work/infratest-service-cdk/infratest-service-cdk/node_modules/jest/bin/jest.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/runner/work/infratest-service-cdk/infratest-service-cdk/node_modules/cliui/build/index.cjs:293:14)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1[25](https://github.com/time-loop/infratest-service-cdk/actions/runs/5148326356/jobs/9269861648?pr=67#step:7:26)0:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
👾 Task "build » test" failed when executing "jest --passWithNoTests --coverageProvider=v8 --updateSnapshot" (cwd: /home/runner/work/infratest-service-cdk/infratest-service-cdk)
Error: Process completed with exit code 1.
```

I took a look and sure enough 
```
❯ yarn why cliui    
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "cliui"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "cliui@7.0.4"
info Reasons this module exists
   - "yargs" depends on it
   - Hoisted from "yargs#cliui"
info Disk size without dependencies: "56KB"
info Disk size with unique dependencies: "380KB"
info Disk size with transitive dependencies: "584KB"
info Number of shared dependencies: 9
=> Found "jsii-release#cliui@8.0.1"
info Reasons this module exists
   - "jsii-release#yargs" depends on it
   - Hoisted from "jsii-release#yargs#cliui"
info Disk size without dependencies: "64KB"
info Disk size with unique dependencies: "388KB"
info Disk size with transitive dependencies: "592KB"
info Number of shared dependencies: 9
✨  Done in 0.24s.
❯ yarn why yargs               
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "yargs"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "yargs@16.2.0"
info Has been hoisted to "yargs"
info Reasons this module exists
   - Hoisted from "standard-version#yargs"
   - Hoisted from "projen#yargs"
   - Hoisted from "jest#jest-cli#yargs"
   - Hoisted from "@time-loop#clickup-projen#projen#yargs"
   - Hoisted from "@time-loop#cdk-ecs-fargate#@time-loop#clickup-projen#projen#yargs"
   - Hoisted from "standard-version#conventional-changelog#conventional-changelog-core#get-pkg-repo#yargs"
info Disk size without dependencies: "452KB"
info Disk size with unique dependencies: "844KB"
info Disk size with transitive dependencies: "1.32MB"
info Number of shared dependencies: 15
=> Found "jsii-release#yargs@17.7.2"
info This module exists because "jsii-release" depends on it.
info Disk size without dependencies: "472KB"
info Disk size with unique dependencies: "864KB"
info Disk size with transitive dependencies: "1.34MB"
info Number of shared dependencies: 15
✨  Done in 0.25s.
```

I hacked in the `wrap-ansi` package and sure enough it's doing an ugly JS `require()`

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/infratest-service-cdk/infratest-service-cdk/node_modules/wrap-ansi/index.js from /home/runner/work/infratest-service-cdk/infratest-service-cdk/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /home/runner/work/infratest-service-cdk/infratest-service-cdk/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/work/infratest-service-cdk/infratest-service-cdk/node_modules/cliui/build/index.cjs:293:14)
...
```

So... what do I need to pin things at to get them working? Is this documented? Anyone else seeing something similar?

Reference https://github.com/time-loop/infratest-service-cdk/pull/67

**Comment by ahammond** [comment]
I eventually resolved it by poaching the package.json and yarn.lock from another, working repo. Then used projen to conform the package.json and... voila. Still... ugly.

**Comment by mrgrain** [comment]
To be honest I think `yarn1` is starting to show it's age. I've run into these weird dependency resolution issues more often recently. 😐

**Comment by nmussy** [comment]
Ran into the same issue, we ended up needing to add a `resolution` for `jackspeak@2.1.1` before regenerating our `yarn.lock` file:

```ts
package.addPackageResolutions('jackspeak@2.1.1');
```

See [storybookjs/storybook/issues/22431#issuecomment-1630086092](https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092)
