### ISSUE TITLE
projen new awscdk-app-ts fails with yarn 3

### ISSUE THREAD

**Issue by jwoehrle** [projen/projen#2800]
I'm trying to create a new awscdk-app-ts using yarn3. 

According to https://github.com/projen/projen/issues/2449#issuecomment-1539827560 I can use `--package-manager=yarn2` to use yarn >= 2

```bash
❯ node --version
v18.16.1
❯ npm --version
9.5.1
❯ yarn --version
3.6.1
❯ npx projen --version
0.71.141
```

The projen command I try to execute is:

`npx projen new awscdk-app-ts --package-manager=yarn2`

however it fails with:

```bash
👾 Installing dependencies...
👾 install | yarn install
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 944ms
➤ YN0000: ┌ Fetch step
➤ YN0019: │ which-boxed-primitive-npm-1.0.2-e214f9ae5a-53ce774c73.zip appears to be unused - removing
➤ YN0019: │ which-typed-array-npm-1.1.11-f37f0cefe2-711ffc8ef8.zip appears to be unused - removing
➤ YN0019: │ write-file-atomic-npm-4.0.2-661baae4aa-5da60bd4ee.zip appears to be unused - removing
➤ YN0019: │ yallist-npm-3.1.1-a568a556b4-48f7bb00dc.zip appears to be unused - removing
➤ YN0019: │ yn-npm-3.1.1-8ad4259784-2c487b0e14.zip appears to be unused - removing
➤ YN0000: └ Completed in 10s 681ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 11s 714ms

> projen-yarn3@0.0.0 eslint
> npx projen eslint

Error: Command failed: npm run eslint --if-present
👾 eslint | eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test build-tools projenrc .projenrc.ts
/bin/sh: eslint: command not found
👾 Task "eslint" failed when executing "eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test build-tools projenrc .projenrc.ts" (cwd: /Users/<USER>/development/projen-yarn3)

    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at exec (/Users/<USER>/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/util.js:15:19)
    at initProject (/Users/<USER>/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js:333:25)
    at Object.handler (/Users/<USER>/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js:69:36)
    at /Users/<USER>/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:1:8993
    at j (/Users/<USER>/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:1:4956)
    at _.handleValidationAndGetResult (/Users/<USER>/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:1:8962)
    at _.applyMiddlewareAndGetResult (/Users/<USER>/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:1:9604) {
  status: 1,
  signal: null,
  output: [
    null,
    null,
    <Buffer f0 9f 91 be 20 1b 5b 33 37 6d 1b 5b 34 6d 65 73 6c 69 6e 74 1b 5b 32 34 6d 20 7c 20 65 73 6c 69 6e 74 20 2d 2d 65 78 74 20 2e 74 73 2c 2e 74 73 78 20 ... 325 more bytes>
  ],
  pid: 14355,
  stdout: null,
  stderr: <Buffer f0 9f 91 be 20 1b 5b 33 37 6d 1b 5b 34 6d 65 73 6c 69 6e 74 1b 5b 32 34 6d 20 7c 20 65 73 6c 69 6e 74 20 2d 2d 65 78 74 20 2e 74 73 2c 2e 74 73 78 20 ... 325 more bytes>
}
```

The same command succeeds if I set yarn to use classic version (`yarn set version classic`) before executing the projen command

**Comment by mrgrain** [comment]
Thanks for reporting! Looks like the call to eslint fails because of Yarn PnP.

In the meantime, you should be able to use `npx projen new awscdk-app-ts --package-manager=yarn2 --no-post`

**Comment by marciocadev** [comment]
you can use `npx projen new awscdk-app-ts --package-manager=npm` too

**Comment by mrgrain** [comment]
Reproduced on `main` (`projen new awscdk-app-ts --package-manager yarn_berry`), still fails with `/bin/sh: eslint: command not found`.

Root cause: the post-scaffold lint in `src/cli/cmds/new.ts:491` is hardcoded to npm:

```ts
exec("npm run eslint --if-present", { cwd: baseDir });
```

For a yarn-berry project this runs outside the Yarn/PnP environment. projen sets no default `nodeLinker` (generated `.yarnrc.yml` is `{}`), so the install uses PnP — no `node_modules/.bin`. `npm run eslint` → `projen eslint` → the task runtime spawns a bare `eslint` via `/bin/sh`, which isn't on PATH under PnP, so it fails. (Running through `yarn` would inject the binary shims and resolve it.)

The auto-detect package-manager change (#4605) hides this for the default `npx` flow (detects npm → `node_modules` linker → works), but explicit yarn-berry still hits it.

Fix direction: run the post-synth lint via the project's package manager (e.g. `yarn eslint`) instead of hardcoded `npm run`.

— posted by Kiro on behalf of @mrgrain
