### ISSUE TITLE
Support "type" field in package.json

### ISSUE THREAD

**Issue by marcioemiranda** [projen/projen#3045]
Hello,

In order to use ESM I need to set the "type" property in package.json to "module". However, this property is not supported in NodePackageOptions. 

Example:
```
{
  "name": "cdktest",
  "version": "0.1.0",
  "type": "module"
}
```

**Comment by mrgrain** [comment]
`project.package.addField('module')`

It probably should be supported, although non of the built-in project types are explicitly ESM tested 🙈

**Comment by marcioemiranda** [comment]
I have added the following snippets to .projenrc.ts

```
tsconfig: {
    compilerOptions: {
      module: 'ESNext',
      target: 'ESNext',
      lib: ['ESNext'],
    },
  },
```

`project.package.addField('type', 'module');`

It worked the first time and generated the fields in tsconfig.json and package.json, but now I get the following error when updating projenrc file:

```
 npx projen
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/marciomiranda/projects/comviva/asa/asa-maintenance-window/.projenrc.ts
    at new NodeError (node:internal/errors:393:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
👾 Synthesis failed: Task "default" failed when executing "ts-node --project tsconfig.dev.json .projenrc.ts" (cwd: /Users/marciomiranda/projects/comviva/asa/asa-maintenance-window)
```

This is my complete projenrc.ts

```
import { awscdk } from 'projen';
//TypeScriptModuleResolution
const project = new awscdk.AwsCdkTypeScriptApp({
  cdkVersion: '2.88.0',
  defaultReleaseBranch: 'main',
  name: 'asa-maintenance-window',
  projenrcTs: true,
  prettier: true,
  prettierOptions: { settings: { singleQuote: true } },
  repository: 'https://github.com/druid-networks/asa-maintenance-window.git',
  tsconfig: {
    compilerOptions: {
      module: 'ESNext',
      target: 'ESNext',
      lib: ['ESNext'],
      //moduleResolution: TypeScriptModuleResolution.NODE,
      //moduleResolution: 'node',
    },
  },

  devDeps: ['@aws-sdk/types@^3.410.0', 'esbuild', '@types/luxon'],
  deps: [
    '@types/aws-lambda',
    '@aws-sdk/client-ssm@^3.410.0',
    'mysql2',
    '@aws-lambda-powertools/logger@^1.12.1',
    '@aws-lambda-powertools/tracer@^1.12.1',
    //'@aws-lambda-powertools/metrics@^2.0.0-alpha.0',
    '@aws-lambda-powertools/parameters@^2.0.0-alpha.0',
    //'@aws-lambda-powertools/commons@^2.0.0-alpha.0',
    '@druid-networks/druid-services-core@^0.0.99',
    '@druid-networks/druid-soap@^0.0.4',
    '@druid-networks/asa-services@^0.0.146',
    '@druid-networks/druid-constructs@^0.0.51',
    'xml2js-xpath',
    'luxon',
  ],
  workflowBootstrapSteps: [
    {
      name: 'Setup NPM Token',
      run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc',
      env: {
        NPM_TOKEN: '${{ secrets.NPM_TOKEN }}',
      },
    },
  ],
});
project.package.addField('type', 'module');
project.synth();
```

**Comment by tinovyatkin** [comment]
@marcioemiranda 
You may try following:
```ts
project.defaultTask?.reset(
  `node --enable-source-maps --no-warnings --loader=ts-node/esm .projenrc.ts`,
);
project.defaultTask?.env('TS_NODE_PROJECT', project.tsconfigDev.fileName);
project.tsconfigDev.file.patch(
  JsonPatch.add('/ts-node', {
    esm: true,
    preferTsExts: true,
    experimentalSpecifierResolution: 'node',
  }),
);
```

**Comment by mrgrain** [comment]
We should totally have a ProjenRcEsm component 😄

**Comment by marcioemiranda** [comment]
Hey @tinovyatkin ,
Thanks for the suggestion, but the result is the same

This is my current projenrc
```
import { JsonPatch, awscdk } from 'projen';
import { TypeScriptModuleResolution } from 'projen/lib/javascript';
const project = new awscdk.AwsCdkTypeScriptApp({
  cdkVersion: '2.88.0',
  defaultReleaseBranch: 'main',
  name: 'asa-maintenance-window',
  projenrcTs: true,
  prettier: true,
  prettierOptions: { settings: { singleQuote: true } },
  repository: 'https://github.com/druid-networks/asa-maintenance-window.git',
  tsconfig: {
    compilerOptions: {
      module: 'ESNext',
      target: 'ESNext',
      lib: ['ESNext'],
      moduleResolution: TypeScriptModuleResolution.NODE,
    },
  },

  devDeps: ['@aws-sdk/types@^3.410.0', 'esbuild', '@types/luxon'],
  deps: [
    '@types/aws-lambda',
    '@aws-sdk/client-ssm@^3.410.0',
    'mysql2',
    '@aws-lambda-powertools/logger@^1.12.1',
    '@aws-lambda-powertools/tracer@^1.12.1',
    //'@aws-lambda-powertools/metrics@^2.0.0-alpha.0',
    '@aws-lambda-powertools/parameters@^2.0.0-alpha.0',
    //'@aws-lambda-powertools/commons@^2.0.0-alpha.0',
    '@druid-networks/druid-services-core@^0.0.99',
    '@druid-networks/druid-soap@^0.0.4',
    '@druid-networks/asa-services@^0.0.146',
    '@druid-networks/druid-constructs@^0.0.51',
    'xml2js-xpath',
    'luxon',
  ],
  workflowBootstrapSteps: [
    {
      name: 'Setup NPM Token',
      run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc',
      env: {
        NPM_TOKEN: '${{ secrets.NPM_TOKEN }}',
      },
    },
  ],
});
project.package.addField('type', 'module');
project.defaultTask?.reset(
  `node --enable-source-maps --no-warnings --loader=ts-node/esm .projenrc.ts`,
);
project.defaultTask?.env('TS_NODE_PROJECT', project.tsconfigDev.fileName);
project.tsconfigDev.file.patch(
  JsonPatch.add('/ts-node', {
    esm: true,
    preferTsExts: true,
    experimentalSpecifierResolution: 'node',
  }),
);
project.synth();
```

and this is the error:

```
$ npx projen
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/marciomiranda/projects/comviva/asa/asa-maintenance-window/.projenrc.ts
    at new NodeError (node:internal/errors:393:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
👾 Synthesis failed: Task "default" failed when executing "ts-node --project tsconfig.dev.json .projenrc.ts" (cwd: /Users/marciomiranda/projects/comviva/asa/asa-maintenance-window)
```

**Comment by tinovyatkin** [comment]
You are seeing this error because your package.json is already changed. So, first remove `type: module` from package.json manually and then run `npx projen`

**Comment by marcioemiranda** [comment]
The contents of file tsconfig.dev.json looks like this:

```
// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
{
  "compilerOptions": {
    "alwaysStrict": true,
    "declaration": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "lib": [
      "ESNext"
    ],
    "module": "ESNext",
    "noEmitOnError": false,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "resolveJsonModule": true,
    "strict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "stripInternal": true,
    "target": "ESNext"
  },
  "include": [
    ".projenrc.js",
    "src/**/*.ts",
    "test/**/*.ts",
    ".projenrc.ts",
    "projenrc/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

**Comment by marcioemiranda** [comment]
Hello again @tinovyatkin , thanks for the prompt response.

I've removed the "type" field from package.json. Now the error is this:

```
$ npx projen
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
/Users/marciomiranda/projects/comviva/asa/asa-maintenance-window/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
.projenrc.ts:1:35 - error TS2792: Cannot find module 'projen'. Did you mean to set the 'moduleResolution' option to 'nodenext', or to add aliases to the 'paths' option?

1 import { JsonPatch, awscdk } from 'projen';
                                    ~~~~~~~~
.projenrc.ts:2:44 - error TS2792: Cannot find module 'projen/lib/javascript'. Did you mean to set the 'moduleResolution' option to 'nodenext', or to add aliases to the 'paths' option?

2 import { TypeScriptModuleResolution } from 'projen/lib/javascript';
                                             ~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/marciomiranda/projects/comviva/asa/asa-maintenance-window/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/marciomiranda/projects/comviva/asa/asa-maintenance-window/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/marciomiranda/projects/comviva/asa/asa-maintenance-window/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/marciomiranda/projects/comviva/asa/asa-maintenance-window/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/Users/marciomiranda/projects/comviva/asa/asa-maintenance-window/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/marciomiranda/projects/comviva/asa/asa-maintenance-window/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 2792, 2792 ]
}
👾 Synthesis failed: Task "default" failed when executing "ts-node --project tsconfig.dev.json .projenrc.ts" (cwd: /Users/marciomiranda/projects/comviva/asa/asa-maintenance-window)
```

**Comment by tinovyatkin** [comment]
So just follow the error message suggestion and add moduleResolution (I would recommend "bundler") to the tsconfig settings

**Comment by marcioemiranda** [comment]
I've added to both tsconfig.json and tsconfig.dev.json manually.
Now it complain about the missing "type" in package.json

```
$ npx projen
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
(node:92816) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/marciomiranda/projects/comviva/asa/asa-maintenance-window/.projenrc.ts:1
import { JsonPatch, awscdk } from 'projen';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module.m._compile (/Users/marciomiranda/projects/comviva/asa/asa-maintenance-window/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/marciomiranda/projects/comviva/asa/asa-maintenance-window/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (/Users/marciomiranda/projects/comviva/asa/asa-maintenance-window/node_modules/ts-node/src/bin.ts:649:14)
👾 Synthesis failed: Task "default" failed when executing "ts-node --project tsconfig.dev.json .projenrc.ts" (cwd: /Users/marciomiranda/projects/comviva/asa/asa-maintenance-window)
```

**Comment by marcioemiranda** [comment]
To give some context, I have this Typescript CDK app with lambda code and CDK infra living together in the same repo.
I would like to use top level await in the lambda code, that's why I need to use ESM.
I use the NodeJsFunction construct to bundle javascript. I could add a tsconfig.json and package.json at the lambda level so that ESBUILD (used by the construct) would use these files instead of the ones generated by projen.

What do you guys recommend in this scenario?

I suppose VsCode would complain about errors, but the build/bundle would work.

I've seen some example code of people using lambdas with ESM and usually they set the type at the project level and the lambda level as well.
Here is an example:
https://github.com/Nantis-GmbH/cdk-lambda-with-layers

**Comment by mrgrain** [comment]
I'm my opinion it's just easier to go all in on ESM, rather than trying to setup a hybrid.

**Comment by tinovyatkin** [comment]
@marcioemiranda 
1. Rollback your changes (to files) and make standard `npx projen` working for you (so you can run it several times in a row)
2. Add changes from [this comment](https://github.com/projen/projen/issues/3045#issuecomment-1783108783), plus changes to tsconfig (`{ module: 'esnext', module: TypeScriptModuleResolution.BUNDLER  }`
3. Run `npx projen`

**Comment by marcioemiranda** [comment]
@tinovyatkin thanks for the reply.
File generation is working now.
However synthesizing the project is failing (this project was created from the ts CDK app template).

Here is the error:
```
$ cdk synth -q --profile tim-dev
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/marciomiranda/projects/comviva/asa/asa-maintenance-window/src/main.ts
    at new NodeError (node:internal/errors:393:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

I suppose I have to manipulate the generation of cdk.json?

The sample application I am using as a reference has this command in cdk json:

`"app": "npx tsx bin/cdktest.ts",`

whereas the one from projen has this command

`"app": "npx ts-node -P tsconfig.json --prefer-ts-exts src/main.ts",`

Can you confirm what should be updated?

**Comment by tinovyatkin** [comment]
@marcioemiranda ESM support in CDK is not a topic covered by official documentation (even while in my team it works well), so you may need to prepare yourself to being able debug quite a few small compatibility issues on your own.

For the error you mentioning in the last message the fix would be to repeat setting from `tsconfig.dev.json` into `tsconfig.json`:
```ts
project.tsconfig.file.patch(
  JsonPatch.add('/ts-node', {
    esm: true,
    preferTsExts: true,
    experimentalSpecifierResolution: 'node',
  }),
);
```

and/or to replace `app` entry in the `cdk.json`
```ts
project
  .tryFindObjectFile("cdk.json")
  ?.patch(
    JsonPatch.replace(
      "/app",
      `node --enable-source-maps --no-warnings --loader=ts-node/esm ${project.srcdir}/${project.appEntrypoint}`
    )
  );
```

**Comment by marcioemiranda** [comment]
Thanks @tinovyatkin , I was able to synthesize the project with these changes. I will close this ticket.
