### ISSUE TITLE
Error when building projen: `Unable to find a JSII dependency named "constructs" as "^10.0.0`

### ISSUE THREAD

**Issue by garysassano** [projen/projen#3115]
```sh
❯ yarn build
yarn run v1.22.19
$ /bin/bash ./projen.bash build
👾 build » default | node .projenrc.js
👾 Installing dependencies...
👾 install | yarn install --check-files
[1/5] Validating package.json...
[2/5] Resolving packages...
warning npm-check-updates > pacote > @npmcli/run-script > node-gyp > make-fetch-happen > cacache > @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
warning standard-version > stringify-package@1.0.1: This module is not used anymore, and has been replaced by @npmcli/package-json
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
👾 build » compile | jsii --silence-warnings=reserved-word
[2023-11-14T06:01:30.973] [ERROR] jsii/package-info - Unable to find a JSII dependency named "constructs" as "^10.0.0". If you meant to include a non-JSII dependency, try adding it to bundledDependencies instead.
jsii compile [PROJECT_ROOT]

Compiles a jsii/TypeScript project

Positionals:
  PROJECT_ROOT  The root of the project to be compiled   [string] [default: "."]

Options:
      --help                      Show help                            [boolean]
      --version                   Show version number                  [boolean]
  -w, --watch                     Watch for file changes and recompile
                                  automatically                        [boolean]
  -r, --project-references        Generate TypeScript project references (also
                                  [package.json].jsii.projectReferences)
                                                                       [boolean]
      --fail-on-warnings, --Werr  Treat warnings as errors             [boolean]
      --silence-warnings          List of warnings to silence (warnings:
                                  reserved-word)           [array] [default: []]
      --strip-deprecated          [EXPERIMENTAL] Hides all @deprecated members
                                  from the API (implementations remain). If an
                                  optional file name is given, only FQNs present
                                  in the file will be stripped.         [string]
      --add-deprecation-warnings  [EXPERIMENTAL] Injects warning statements for
                                  all deprecated elements, to be printed at
                                  runtime             [boolean] [default: false]
      --generate-tsconfig         Name of the typescript configuration file to
                                  generate with compiler settings
                                             [string] [default: "tsconfig.json"]
      --compress-assembly         Emit a compressed version of the assembly
                                                      [boolean] [default: false]
  -v, --verbose                   Increase the verbosity of output       [count]

Error: Error loading assembly from file /home/user/github/projen/node_modules/constructs/.jsii:
TypeError: ajv_1.default is not a constructor
    at loadAssemblyFromFile (/home/user/github/projen/node_modules/jsii/node_modules/@jsii/spec/lib/assembly-utils.js:129:15)
    at DependencyResolver.loadAssemblyAndRecurse (/home/user/github/projen/node_modules/jsii/lib/project-info.js:206:58)
    at DependencyResolver.resolveDependency (/home/user/github/projen/node_modules/jsii/lib/project-info.js:198:34)
    at DependencyResolver.discoverDependencyTree (/home/user/github/projen/node_modules/jsii/lib/project-info.js:153:33)
    at loadProjectInfo (/home/user/github/projen/node_modules/jsii/lib/project-info.js:50:31)
    at Object.handler (/home/user/github/projen/node_modules/jsii/lib/main.js:81:105)
    at /home/user/github/projen/node_modules/yargs/build/index.cjs:1:8993
    at j (/home/user/github/projen/node_modules/yargs/build/index.cjs:1:4956)
    at _.handleValidationAndGetResult (/home/user/github/projen/node_modules/yargs/build/index.cjs:1:8962)
    at _.applyMiddlewareAndGetResult (/home/user/github/projen/node_modules/yargs/build/index.cjs:1:9604)
👾 Task "build » compile" failed when executing "jsii --silence-warnings=reserved-word" (cwd: /home/user/github/projen)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mrgrain** [comment]
Hey @garysassano  thanks for the report! `constructs` is indeed a new addition. 

The command looks like you are trying to build `projen` itself? I am doing this a few times a day without issues. So is CI/CD. Could you try this again with a fresh copy?

**Comment by garysassano** [comment]
Yes, I'm trying to build projen. I've just tryed a fresh install and got same error.

I set yarn version to classic since stable (v4.0.2) isn't able to build.

**Comment by mrgrain** [comment]
Hmm. You definitely need yarn classic to build projen, that's correct. Are you somehow using `PnP` maybe?

**Comment by garysassano** [comment]
No, but I'm using WSL2 if that can help.
