### ISSUE TITLE
projen new cdk8s-construct generates non working package.json/yarn.lock combinations

### ISSUE THREAD

**Issue by pgollucci** [projen/projen#327]
```shell
mkdir p6-cdk8s-hello-world
cd p6-cdk8s-hello-world
projen new cdk8s-construct
npx projen # delta, because the global above is older
yarn
yarn build
```

```text
.....
jsii --silence-warnings=reserved-word --no-fix-peer-dependencies && jsii-docgen
Error: Error: Declared dependency on version 2.0.2 of constructs, but version 3.2.27 was found
    at _loadDependencies (/Users/pgollucci/src/github.com/p6m7g8/p6-cdk8s-hello-world/node_modules/jsii/lib/project-info.js:140:19)
    at async _loadDependencies (/Users/pgollucci/src/github.com/p6m7g8/p6-cdk8s-hello-world/node_modules/jsii/lib/project-info.js:150:13)
    at async Object.loadProjectInfo (/Users/pgollucci/src/github.com/p6m7g8/p6-cdk8s-hello-world/node_modules/jsii/lib/project-info.js:66:30)
    at async /Users/pgollucci/src/github.com/p6m7g8/p6-cdk8s-hello-world/node_modules/jsii/bin/jsii.js:54:25
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

pulling out the Error

`Error: Error: Declared dependency on version 2.0.2 of constructs, but version 3.2.27 was found
    at _loadDependencies (/Users/pgollucci/src/github.com/p6m7g8/p6-cdk8s-hello-world/node_modules/jsii/lib/project-info.js:140:19)`

Step 1) Modify .projenrc.js to 
```diff
git diff .projenrc.js 
diff --git i/.projenrc.js w/.projenrc.js
index 8296478..cfb9597 100644
--- i/.projenrc.js
+++ w/.projenrc.js
@@ -3,7 +3,7 @@ const { ConstructLibraryCdk8s } = require('projen');
 const project = new ConstructLibraryCdk8s({
   authorAddress: "pgollucci@p6m7g8.com",
   authorName: "Philip M. Gollucci",
-  cdk8sVersion: "0.28.0",
+  cdk8sVersion: "1.0.0-beta.3",
   name: "p6-cdk8s-hello-world",
   repository: "https://github.com/pgollucci/p6-cdk8s-hello-world.git",
 ```
Step 2) Rerun `npx projen`
Works

Step 3) `yarn build`
...
```text
Error: Error: Declared dependency on version ^3.2.34 of constructs, but version 3.2.27 was found
```

**Comment by pgollucci** [comment]
This may yet be in cdk8s but we should still update the cdk8s version
