### ISSUE TITLE
Error messages for npx projen new are not helpful

### ISSUE THREAD

**Issue by Spaideri** [projen/projen#3303]
## Update

- `--from <package-name>` is used to create new projects from external packages
- The user accidentally passed the project type to `--from`, so projen attempt to install use the project type as a package name
- Clearly the error message isn't very good here and should be improved

---

## Original issue 

Tried with multiple different templates and they all failed

## typescript
```npx projen new --from typescript```

```
npx projen new --from typescript
/Users/username/path/to/my/project/dir
└── (empty)


added 2 packages in 1s

10 packages are looking for funding
  run `npm fund` for details
👾 installing external module typescript...

added 1 package, and audited 71 packages in 542ms

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Error: Cannot find module 'typescript/.jsii'
Require stack:
- /Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js
- /Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/index.js
- /Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/bin/projen
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.resolve (node:internal/modules/helpers:187:19)
    at initProjectFromModule (/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js:234:44)
    at Object.handler (/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js:95:26)
    at /Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:1:8993
    at j (/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:1:4956)
    at _.handleValidationAndGetResult (/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:1:8962)
    at _.applyMiddlewareAndGetResult (/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:1:9604)
    at _.runCommand (/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:1:7231)
    at [runYargsParserAndExecuteCommands] (/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:1:58912) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js',
    '/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/index.js',
    '/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/bin/projen'
  ]
}
```

## awscdk-app-ts

```npx projen new --from awscdk-app-ts```

```
/Users/username/path/to/my/project/dir
└── (empty)


added 2 packages in 657ms

10 packages are looking for funding
  run `npm fund` for details
👾 installing external module awscdk-app-ts...
Error: Command failed: npm install --save --save-dev -f --no-package-lock --prefix="/Users/username/path/to/my/project/dir" awscdk-app-ts
npm WARN using --force Recommended protections disabled.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/awscdk-app-ts - Not found
npm ERR! 404
npm ERR! 404  'awscdk-app-ts@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /Users/username/.npm/_logs/2024-01-26T07_18_28_978Z-debug-0.log

    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at exec (/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/util.js:15:19)
    at installPackage (/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/util.js:21:21)
    at initProjectFromModule (/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js:231:50)
    at Object.handler (/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js:95:26)
    at /Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:1:8993
    at j (/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:1:4956)
    at _.handleValidationAndGetResult (/Users/username/.npm/_npx/80cfb0dc84733c29/node_modules/projen/node_modules/yargs/build/index.cjs:1:8962) {
  status: 1,
  signal: null,
  output: [
    null,
    null,
    <Buffer 6e 70 6d 20 57 41 52 4e 20 75 73 69 6e 67 20 2d 2d 66 6f 72 63 65 20 52 65 63 6f 6d 6d 65 6e 64 65 64 20 70 72 6f 74 65 63 74 69 6f 6e 73 20 64 69 73 ... 410 more bytes>
  ],
  pid: 80408,
  stdout: null,
  stderr: <Buffer 6e 70 6d 20 57 41 52 4e 20 75 73 69 6e 67 20 2d 2d 66 6f 72 63 65 20 52 65 63 6f 6d 6d 65 6e 64 65 64 20 70 72 6f 74 65 63 74 69 6f 6e 73 20 64 69 73 ... 410 more bytes>
}
```

My environment
OS: macOS 14.2.1 (23C71)
Node version: v20.10.0

**Comment by mrgrain** [comment]
For anyone coming here:

- `--from <package-name>` is used to create new projects from external packages
- The user accidentally passed the project type to `--from`, so projen attempt to install use the project type as a package name
- Clearly the error message isn't very good here and should be improved

**Comment by adamelkhayyat** [comment]
I've faced similar experiences when starting with Projen, will give improving this a shot in #3385.
