### ISSUE TITLE
Failed to create awscdk-construct using projen on Cloud9 using npm 6.14.8

### ISSUE THREAD

**Issue by readybuilderone** [projen/projen#344]
I tried to create the awscdk-construct on a new create cloud9 running Amazon Linux2, but failed.
I tried on my Macbook and Cloud9, both failed with the same error. 
Anyone met the same problem?

Here is the details: 
``` shell
yihuihan:~/environment $ npm --version
6.14.8
yihuihan:~/environment $ mkdir foo
yihuihan:~/environment $ cd foo
yihuihan:~/environment/foo $ npx projen new awscdk-construct
npx: installed 64 in 4.663s
SyntaxError: Unexpected token $ in JSON at position 0
    at JSON.parse (<anonymous>)
    at renderDefault (/home/ec2-user/.npm/_npx/6444/lib/node_modules/projen/lib/cli/cmds/new.js:187:89)
    at builder (/home/ec2-user/.npm/_npx/6444/lib/node_modules/projen/lib/cli/cmds/new.js:46:48)
    at Object.runCommand (/home/ec2-user/.npm/_npx/6444/lib/node_modules/projen/node_modules/yargs/build/index.cjs:395:35)
    at Object.parseArgs [as _parseArgs] (/home/ec2-user/.npm/_npx/6444/lib/node_modules/projen/node_modules/yargs/build/index.cjs:2681:57)
    at Object.runCommand (/home/ec2-user/.npm/_npx/6444/lib/node_modules/projen/node_modules/yargs/build/index.cjs:402:36)
    at Object.parseArgs [as _parseArgs] (/home/ec2-user/.npm/_npx/6444/lib/node_modules/projen/node_modules/yargs/build/index.cjs:2681:57)
    at Function.get [as argv] (/home/ec2-user/.npm/_npx/6444/lib/node_modules/projen/node_modules/yargs/build/index.cjs:2635:25)
    at main (/home/ec2-user/.npm/_npx/6444/lib/node_modules/projen/lib/cli/index.js:14:21)
    at Object.<anonymous> (/home/ec2-user/.npm/_npx/6444/lib/node_modules/projen/lib/cli/index.js:21:1)
```

Is this a bug? Please confirm.

**Comment by Chriscbr** [comment]
Can you try running `npx projen --version` and show what version is being run?

I think this could be a bug with the way we are processing macros [here](https://github.com/projen/projen/blob/master/src/cli/macros.ts#L4) which occurs when git has not been configured or if git doesn't have some of its config values configured like `user.name`.

As a temporary workaround, can you try setting this option and see if it that fixes the bug?
```
git config --global user.name "readybuilderone"
```

**Comment by readybuilderone** [comment]
Thanks @Chriscbr , you're right, git config did solve the problem.
The projen version is 0.5.8, here is the details:
``` shell
$ npx projen --version
npx: installed 64 in 4.608s
0.5.8
```

Thanks again.
