### ISSUE TITLE
(feat:subproject): throw error no github support

### ISSUE THREAD

**Issue by guillaumemaka** [projen/projen#354]
So I try to move from CompositeProject to the subprojects.

Here the version I use:
```
npx projen --version
0.5.2
```

if I write a similar example of test/subprojects.js

```js
new Project({
  parent: comp,
  outdir: 'cdk',
  packageManager: NodePackageManager.YARN,
});

new Project({
  parent: comp,
  outdir: 'lambda-function-1',
  packageManager: NodePackageManager.YARN,
});

new Project({
  parent: comp,
  outdir: 'lambda-function-2',
  packageManager: NodePackageManager.YARN,
});

comp.synth();

```

It works fine!
```console
 npx projen
🤖 Synthesizing project...
🤖 Synthesis complete
🤖 Synthesis complete
🤖 Synthesis complete
🤖 Synthesis complete
```

But when I try mixing project types:

```js
new AwsCdkTypeScriptApp({
  outdir: 'cdk',
  parent: comp,
  cdkVersion: '1.75.0',
  cdkVersionPinning: true,
  packageManager: NodePackageManager.YARN,
});

new TypeScriptAppProject({
  outdir: 'lambda-function-1',
  parent: comp,
  packageManager: NodePackageManager.YARN,
});

new TypeScriptAppProject({
  outdir: 'lambda-function-2',
  parent: comp,
  packageManager: NodePackageManager.YARN,
});

comp.synth();
```

I got an error:

```console
❯ npx projen
🤖 Synthesizing project...
Error: no github support
  at AwsCdkTypeScriptApp.createBuildWorkflow (/Users/guillaume/Developer/scratch/projen-subproject-example/node_modules/projen/lib/node-project.js:734:19)
    at new NodeProject (/Users/guillaume/Developer/scratch/projen-subproject-example/node_modules/projen/lib/node-project.js:193:51)
    at new TypeScriptProject (/Users/guillaume/Developer/scratch/projen-subproject-example/node_modules/projen/lib/typescript.js:24:9)
    at new TypeScriptAppProject (/Users/guillaume/Developer/scratch/projen-subproject-example/node_modules/projen/lib/typescript.js:259:9)
    at new AwsCdkTypeScriptApp (/Users/guillaume/Developer/scratch/projen-subproject-example/node_modules/projen/lib/awscdk-app-ts.js:31:9)
    at Object.<anonymous> (/Users/guillaume/Developer/scratch/projen-subproject-example/.projenrc.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

Also it seems impossible to have a root (.) project and subprojects (./foo, ./bar) like:

```
├── cdk <---- subproject
│   ├── src
│   ├── test
│   ├── LICENSE
│   ├── cdk.json
│   ├── tsconfig.jest.json
│   ├── tsconfig.json
│   ├── version.json
│   ├── yarn-error.log
│   └── yarn.lock
├── src <------ root project
│   ├── lib
│   ├── models
│   ├── templates
│   └── index.js
├── LICENSE
├── package.jsonn
├── version.json
└── yarn.lock
```

With the deprecated CompositeProject I can achieve the above structure:

```js
const cdk = new AwsCdkTypeScriptApp({
  cdkVersion: '1.75.0',
  cdkVersionPinning: true,
  packageManager: NodePackageManager.YARN,
});

const lambda = new TypeScriptAppProject({
  packageManager: NodePackageManager.YARN,
});

const comp = new CompositeProject({
  projects: {
    {path: 'cdk/', project: cdk },
    {path: '.', project: lambda },
  }
})

comp.synth();
```

https://github.com/projen/projen/blob/0a06f751e05e0dbc81966fcc09bfcba0fe981690/src/project.ts#L113-L115

**Comment by Chriscbr** [comment]
I'm sorry that the subproject feature still has some hiccups in it. I did some debugging and figured out that the issue is that subprojects are not initialized with a `Github` component, so under the default settings it will try to synthesize GitHub actions/workflows, but fail. This can be temporarily fixed by adding three more options:

```ts
const lambda = new TypeScriptAppProject({
  packageManager: NodePackageManager.YARN,
});

const cdk = new AwsCdkTypeScriptApp({
  parent: lambda,
  outdir: 'cdk',
  cdkVersion: '1.75.0',
  cdkVersionPinning: true,
  packageManager: NodePackageManager.YARN,
  buildWorkflow: false, // !
  releaseWorkflow: false, // !
  rebuildBot: false, // !
});

lambda.synth();
```

Right now projen does not have a system for combining GitHub action workflows of different subprojects into the `.github` folder in the root directory, so I think that is something that still needs to be scoped out as a feature (related: #298). It's still possible you can manually construct and add workflows corresponding to the subprojects via `rootProject.github.addWorkflow(new GithubWorkflow(...))` but it's definitely not as convenient... Hope this helps.

**Comment by guillaumemaka** [comment]
In fact I use `GithubWorkflow() class` for declaring my workflows.

**Comment by guillaumemaka** [comment]
Also if I declare this structure:
```ts
const comp = new Project();

const defaultOpts = {
  releaseWorkflow: false,
  buildWorkflow: false,
  packageManager: NodePackageManager.YARN,
};
// Test mixed

new AwsCdkTypeScriptApp({
  outdir: 'cdk',
  parent: comp,
  cdkVersion: '1.76.0',
  cdkVersionPinning: true,
  ...defaultOpts,
});

new TypeScriptAppProject({
  outdir: '.',
  parent: comp,
  ...defaultOpts,
});
```

I got this error

```
Une exception s'est produite : Error: there is already a file under .gitignore
  at new FileBase (/Users/guillaume/Developer/scratch/projen-subproject-example/node_modules/projen/lib/file.js:24:19)
    at new IgnoreFile (/Users/guillaume/Developer/scratch/projen-subproject-example/node_modules/projen/lib/ignore-file.js:14:9)
    at new Project (/Users/guillaume/Developer/scratch/projen-subproject-example/node_modules/projen/lib/project.js:55:26)
    at new NodeProject (/Users/guillaume/Developer/scratch/projen-subproject-example/node_modules/projen/lib/node-project.js:50:9)
    at new TypeScriptProject (/Users/guillaume/Developer/scratch/projen-subproject-example/node_modules/projen/lib/typescript.js:24:9)
    at new TypeScriptAppProject (/Users/guillaume/Developer/scratch/projen-subproject-example/node_modules/projen/lib/typescript.js:259:9)
    at Object.<anonymous> (/Users/guillaume/Developer/scratch/projen-subproject-example/.projenrc.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)

```

**Comment by Chriscbr** [comment]
That issue caused by the fact that `Project` and `TypeScriptAppProject` in your example both try synthesizing several files that end up in the same location, including `.gitignore`. I'm not really sure if `outdir: '.'` is currently supported with subprojects, but maybe it is something that we should consider?

Is it possible for you to restructure your projects to avoid using `outdir: '.'`, perhaps by removing `const comp = new Project();` ?

**Comment by guillaumemaka** [comment]
I could try to move my root project to his own directory alongside the cdk one. But if I remove the `comp` I need to call `synth()` on both project.

**Comment by guillaumemaka** [comment]
```
const defaultOpts = {
  releaseWorkflow: false,
  buildWorkflow: false,
  packageManager: NodePackageManager.YARN,
};
// Test mixed

new AwsCdkTypeScriptApp({
  outdir: 'cdk',
  // parent: comp,
  cdkVersion: '1.76.0',
  cdkVersionPinning: true,
  ...defaultOpts,
}).synth();

new TypeScriptAppProject({
  outdir: '.',
  // parent: comp,
  ...defaultOpts,
}).synth();
```

Works for me as workaround.
