### ISSUE TITLE
Adding `bumpFiles` to `versionrcOptions` breaks the `bump` task

### ISSUE THREAD

**Issue by toxygene** [projen/projen#3680]
I wanted to create a plain text `version.txt` file using the `versionrcOptions` option for a `TypeScriptProject` project. When I added the `bumpFiles` entry, however, the `bump` task stopped "bumping" the file version.

I believe the problem is https://github.com/projen/projen/blob/main/src/release/bump-version.ts#L313.

When I try to run similar code via `ts-node`, I get the following:

```
➜  my-test git:(main) npx ts-node
> {bumpFiles: [{filename: 'dist/version.txt', type: 'json'}], ...{bumpFiles: []}}
<repl>.ts:4:3 - error TS2783: 'bumpFiles' is specified more than once, so this usage will be overwritten.

4 ({bumpFiles: [{filename: 'dist/version.txt', type: 'json'}], ...{bumpFiles: []}})
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  <repl>.ts:4:62
    4 ({bumpFiles: [{filename: 'dist/version.txt', type: 'json'}], ...{bumpFiles: []}})
                                                                   ~~~~~~~~~~~~~~~~~~
    This spread always overwrites this property.
```

The following `.projenrc.ts` can be used to reproduce the issue:

```typescript
import { javascript, typescript } from 'projen';
import { ReleaseTrigger } from 'projen/lib/release';
const project = new typescript.TypeScriptProject({
  defaultReleaseBranch: 'main',
  name: 'my-test',
  packageManager: javascript.NodePackageManager.NPM,
  projenrcTs: true,
  releaseTrigger: ReleaseTrigger.manual({
    gitPushCommand: '',
  }),
  versionrcOptions: {
    bumpFiles: [
      {
        filename: 'my-version.txt',
        type: 'plain-text',
      },
    ],
  },
});
project.synth();
```

After replacing the `.projenrc.ts` with the above code, the error can be seen in the following shell output:

```
➜  my-test git:(main) npx projen
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
👾 Installing dependencies...
👾 install | npm install

up to date, audited 704 packages in 776ms

129 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  my-test git:(main) ✗ git add .
➜  my-test git:(main) ✗ git commit -m "fix: configure projen to demonstrate versionrc issue"
[main db07c63] fix: configure projen to demonstrate versionrc issue
 7 files changed, 39 insertions(+), 88 deletions(-)
 delete mode 100644 .github/workflows/release.yml
➜  my-test git:(main) npx projen release
👾 release | rm -fr dist
👾 release » bump | condition: ! git log --oneline -1 | grep -q "chore(release):"
👾 release » bump | '/Users/justin.hendrickson/.asdf/installs/nodejs/20.15.0/bin/node' '/Users/justin.hendrickson/temp/my-test/node_modules/projen/lib/release/bump-version.task.js'
👾 Update /Users/justin.hendrickson/temp/my-test/package.json to latest resolved version: 0.0.0
✖ skip version bump on first release
✔ created /Users/justin.hendrickson/temp/my-test/dist/changelog.md
✔ outputting changes to /Users/justin.hendrickson/temp/my-test/dist/changelog.md
👾 release » build » default | ts-node --project tsconfig.dev.json .projenrc.ts
👾 release » build » compile | tsc --build
👾 release » build » test | jest --passWithNoTests --updateSnapshot
 PASS  test/hello.test.ts
  ✓ hello (1 ms)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
 index.ts |     100 |      100 |     100 |     100 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.988 s, estimated 1 s
Ran all test suites.
👾 release » build » test » eslint | eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern  src test build-tools projenrc .projenrc.ts
👾 release » build » package | mkdir -p dist/js
👾 release » build » package | npm pack --pack-destination dist/js
npm notice
npm notice 📦  my-test@0.0.0
npm notice Tarball Contents
npm notice 15B .tool-versions
npm notice 11.4kB LICENSE
npm notice 14B README.md
npm notice 55B lib/index.d.ts
npm notice 617B lib/index.js
npm notice 2.3kB package.json
npm notice Tarball Details
npm notice name: my-test
npm notice version: 0.0.0
npm notice filename: my-test-0.0.0.tgz
npm notice package size: 5.5 kB
npm notice unpacked size: 14.4 kB
npm notice shasum: 55d3ad0b3a65151bdde7615b5725abbe256c99a7
npm notice integrity: sha512-ljSHfGhaHSFF8[...]86glv4bf5VQbg==
npm notice total files: 6
npm notice
my-test-0.0.0.tgz
👾 release » unbump | '/Users/justin.hendrickson/.asdf/installs/nodejs/20.15.0/bin/node' '/Users/justin.hendrickson/temp/my-test/node_modules/projen/lib/release/reset-version.task.js'
👾 release | git diff --ignore-space-at-eol --exit-code
👾 release » publish:git | condition: ! git log --oneline -1 | grep -q "chore(release):"
👾 release » publish:git | '/Users/justin.hendrickson/.asdf/installs/nodejs/20.15.0/bin/node' '/Users/justin.hendrickson/temp/my-test/node_modules/projen/lib/release/update-changelog.task.js'
[main 249377b] chore(release): 0.0.0
 1 file changed, 8 insertions(+)
 create mode 100644 CHANGELOG.md
👾 release » publish:git | '/Users/justin.hendrickson/.asdf/installs/nodejs/20.15.0/bin/node' '/Users/justin.hendrickson/temp/my-test/node_modules/projen/lib/release/tag-version.task.js'
➜  my-test git:(main) git commit --allow-empty --message "fix: a sample commit to force a new release version number"
[main 91eedda] fix: a sample commit to force a new release version number
➜  my-test git:(main) npx projen release
👾 release | rm -fr dist
👾 release » bump | condition: ! git log --oneline -1 | grep -q "chore(release):"
👾 release » bump | '/Users/justin.hendrickson/.asdf/installs/nodejs/20.15.0/bin/node' '/Users/justin.hendrickson/temp/my-test/node_modules/projen/lib/release/bump-version.task.js'
👾 Update /Users/justin.hendrickson/temp/my-test/package.json to latest resolved version: 0.0.0
👾 Number of commits since v0.0.0: 1
✔ created /Users/justin.hendrickson/temp/my-test/dist/changelog.md
✔ outputting changes to /Users/justin.hendrickson/temp/my-test/dist/changelog.md
👾 release » build » default | ts-node --project tsconfig.dev.json .projenrc.ts
👾 release » build » compile | tsc --build
👾 release » build » test | jest --passWithNoTests --updateSnapshot
 PASS  test/hello.test.ts
  ✓ hello (1 ms)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
 index.ts |     100 |      100 |     100 |     100 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.911 s, estimated 1 s
Ran all test suites.
👾 release » build » test » eslint | eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern  src test build-tools projenrc .projenrc.ts
👾 release » build » package | mkdir -p dist/js
👾 release » build » package | npm pack --pack-destination dist/js
npm notice
npm notice 📦  my-test@0.0.0
npm notice Tarball Contents
npm notice 15B .tool-versions
npm notice 99B CHANGELOG.md
npm notice 11.4kB LICENSE
npm notice 14B README.md
npm notice 55B lib/index.d.ts
npm notice 617B lib/index.js
npm notice 2.3kB package.json
npm notice Tarball Details
npm notice name: my-test
npm notice version: 0.0.0
npm notice filename: my-test-0.0.0.tgz
npm notice package size: 5.6 kB
npm notice unpacked size: 14.5 kB
npm notice shasum: e12cb00db4edec9a3243fff11abb22ecc1c2c90a
npm notice integrity: sha512-5P9cHDUU9XxtF[...]m1KpoIjuotTHQ==
npm notice total files: 7
npm notice
my-test-0.0.0.tgz
👾 release » unbump | '/Users/justin.hendrickson/.asdf/installs/nodejs/20.15.0/bin/node' '/Users/justin.hendrickson/temp/my-test/node_modules/projen/lib/release/reset-version.task.js'
👾 release | git diff --ignore-space-at-eol --exit-code
👾 release » publish:git | condition: ! git log --oneline -1 | grep -q "chore(release):"
👾 release » publish:git | '/Users/justin.hendrickson/.asdf/installs/nodejs/20.15.0/bin/node' '/Users/justin.hendrickson/temp/my-test/node_modules/projen/lib/release/update-changelog.task.js'
[main 02d0f11] chore(release): 0.0.0
 1 file changed, 7 insertions(+)
👾 release » publish:git | '/Users/justin.hendrickson/.asdf/installs/nodejs/20.15.0/bin/node' '/Users/justin.hendrickson/temp/my-test/node_modules/projen/lib/release/tag-version.task.js'
Error: Command failed: git tag v0.0.0 -a -F /Users/justin.hendrickson/temp/my-test/dist/changelog.md
fatal: tag 'v0.0.0' already exists

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at Object.exec (/Users/justin.hendrickson/temp/my-test/node_modules/projen/lib/util.js:15:19)
    at git (/Users/justin.hendrickson/temp/my-test/node_modules/projen/lib/release/tag-version.js:20:32)
    at tag (/Users/justin.hendrickson/temp/my-test/node_modules/projen/lib/release/tag-version.js:33:5)
👾 Task "release » publish:git" failed when executing "'/Users/justin.hendrickson/.asdf/installs/nodejs/20.15.0/bin/node' '/Users/justin.hendrickson/temp/my-test/node_modules/projen/lib/release/tag-version.task.js'" (cwd: /Users/justin.hendrickson/temp/my-test)
```

**Comment by mrgrain** [comment]
Ah yes. We need to properly merge the `packageFiles` and `bumpFiles` arrays here
https://github.com/projen/projen/blob/f212132bd15ab0b608beebdd5795c16f631f13cb/src/release/bump-version.ts#L292

And I guess also make sure that any required options are enforced.

**Comment by Provokke** [comment]
Is this still wanted? I can open a PR that merges the packageFiles and bumpFiles arrays from versionrcOptions with the ones projen sets, instead of the later spread overwriting them, with a test covering a custom bumpFiles entry.

**Comment by mrgrain** [comment]
@Provokke yes please!
