### ISSUE TITLE
Random stack properties are getting added to the constructs created by Projen package

### ISSUE THREAD

**Issue by TirushV** [projen/projen#3960]
1. We have bunch of custom cdk constructs. 
2. When i run `npx projen build` the build updates the `api.md` with the changes made in the constructs which is expected. 
3. But the issue was its adding random properties like `notificationArns`, `permissionBoundary` to all constructs as a required stack properties. 
4. We have not made any changes to the constructs but not sure why this is adding/updating api.md with not made changes.

Eg:

`[API.md]: Added notificationArns property to ApiGatewayStackProps, AppBuildStackProps, AppStackProps, EcsClusterProps, EcsStackProps, FrontendAppStackProps, and GHAEcsStackProps to allow specifying SNS Topic ARNs that will receive stack events`

**Comment by mrgrain** [comment]
You probably have updated your version of `aws-cdk-lib`, which added this to `StackProps` in https://github.com/aws/aws-cdk/pull/31107

The generated `API.md` file contains all props from parent classes and interfaces, so this is entirely expected.

**Comment by TirushV** [comment]
Im using `"aws-cdk-lib": "^2.152.0"`, version currently under package.json

**Comment by mrgrain** [comment]
`^2.152.0` indicates you are happy to receive any v2 version as long as it's newer or equal to `2.152.0`

**Comment by TirushV** [comment]
Ok got it. Projen autogenerates this package.json file do we have any parameter to enforce it without `^`?

**Comment by mrgrain** [comment]
There is this: https://projen.io/docs/api/awscdk?_highlight=cdkversionpi#projen.awscdk.AwsCdkDepsCommonOptions.property.cdkVersionPinning

But this tells me that something else is not going the way it should.
What project type are you usin? hat does you full `package.json` look like

**Comment by TirushV** [comment]
```

Error: Declared dependency on version 2.152.0 of aws-cdk-lib, but version 2.166.0 was found
    at DependencyResolver.discoverDependencyTree (/Users/tirush.venamadala/Documents/custom-cdk-constructs/node_modules/jsii/lib/project-info.js:165:23)
    at loadProjectInfo (/Users/tirush.venamadala/Documents/custom-cdk-constructs/node_modules/jsii/lib/project-info.js:51:31)
    at Object.handler (/Users/tirush.venamadala/Documents/custom-cdk-constructs/node_modules/jsii/lib/main.js:121:105)
    at /Users/tirush.venamadala/Documents/custom-cdk-constructs/node_modules/jsii/node_modules/yargs/build/index.cjs:1:8993
    at j (/Users/tirush.venamadala/Documents/custom-cdk-constructs/node_modules/jsii/node_modules/yargs/build/index.cjs:1:4956)
    at _.handleValidationAndGetResult (/Users/tirush.venamadala/Documents/custom-cdk-constructs/node_modules/jsii/node_modules/yargs/build/index.cjs:1:8962)
    at _.applyMiddlewareAndGetResult (/Users/tirush.venamadala/Documents/custom-cdk-constructs/node_modules/jsii/node_modules/yargs/build/index.cjs:1:9604)
    at _.runCommand (/Users/tirush.venamadala/Documents/custom-cdk-constructs/node_modules/jsii/node_modules/yargs/build/index.cjs:1:7231)
    at [runYargsParserAndExecuteCommands] (/Users/tirush.venamadala/Documents/custom-cdk-constructs/node_modules/jsii/node_modules/yargs/build/index.cjs:1:58912)
    at te.parse (/Users/tirush.venamadala/Documents/custom-cdk-constructs/node_modules/jsii/node_modules/yargs/build/index.cjs:1:40478)
👾 Task "build » compile" failed when executing "jsii --silence-warnings=reserved-word" (cwd: /Users/tirush.venamadala/Documents/custom-cdk-constructs

```

I added the cdkversion pinning but getting above error


Here is my projen file
```

import { awscdk } from 'projen';
import { NodePackageManager } from 'projen/lib/javascript';

const goPackageName = 'bclxyzconstructsgo';

const project = new awscdk.AwsCdkConstructLibrary({
  packageManager: NodePackageManager.YARN_CLASSIC,
  author: 'TirushV',
  authorAddress: 'tirush.venamadala@fox.com',
  cdkVersion: '2.152.0',
  cdkVersionPinning: true,
  jsiiVersion: '~5.4.0',
  name: '@bclxyz/custom-cdk-constructs',
  projenrcTs: true,
  minNodeVersion: '18.20.2',
  repositoryUrl: 'https://github.com/bclxyz/custom-cdk-constructs.git',
  deps: ['@aws-cdk/aws-lambda-python-alpha'],
  prettier: true,
  prettierOptions: {
    settings: {
      printWidth: 80,
      tabWidth: 2,
      useTabs: false,
      semi: true,
      singleQuote: true,
      bracketSpacing: true,
    },
  },
  jestOptions: {
    jestVersion: '29',
  },
  eslintOptions: {
    dirs: ['src'],
    fileExtensions: [],
    prettier: true,
  },
  npmRegistryUrl: 'https://npm.pkg.github.com',
  npmTokenSecret: 'GITHUB_TOKEN',
  defaultReleaseBranch: 'main',
  npmDistTag: 'latest',
  majorVersion: 1,
  projenVersion: '0.87.2',
  entrypoint: 'lib/index.js',
  publishToGo: {
    moduleName: 'github.com/bclxyz/custom-cdk-constructs', // Go module path including subdirectory
    packageName: goPackageName, // Optional: the Go package name
    gitBranch: 'main', // Branch to commit to
    gitUserName: 'github-actions', // Git user name for commits
    gitUserEmail: 'github-actions@github.com', // Git user email for commits
    githubUseSsh: true, // Use SSH for Git operations
    // versionSuffix: "", // Optional: suffix to append to the version
  },
});

project.prettier?.ignoreFile?.include('API.md');

// very important
project.gitignore.include(`${goPackageName}/**/*.tgz`);

// if not set, 2 CI will be triggered and the second one is useless and will fail. Go self-mutates the repo.
const releaseWorkflow = project.github?.tryFindWorkflow('release');
if (releaseWorkflow?.file) {
  releaseWorkflow.file.addOverride('on.push.paths-ignore', [
    `${goPackageName}/**`,
  ]);
}

project.synth();
```

**Comment by mrgrain** [comment]
```
Error: Declared dependency on version 2.152.0 of aws-cdk-lib, but version 2.166.0 was found
```

You got yourself in a pickle that projen cannot currently resolve for you.  You probably need to delete `node_modules` and `yarn.lock` then run `yarn` to make it work again.

**Comment by mrgrain** [comment]
> Here is my projen file

Thanks that looks all good. Can you share the `package.json` as well?

**Comment by TirushV** [comment]
```
{
  "name": "@bclxyz/custom-cdk-constructs",
  "repository": {
    "type": "git",
    "url": "https://github.com/bclxyz/custom-cdk-constructs.git"
  },
  "scripts": {
    "build": "npx projen build",
    "bump": "npx projen bump",
    "clobber": "npx projen clobber",
    "compat": "npx projen compat",
    "compile": "npx projen compile",
    "default": "npx projen default",
    "docgen": "npx projen docgen",
    "eject": "npx projen eject",
    "eslint": "npx projen eslint",
    "package": "npx projen package",
    "package-all": "npx projen package-all",
    "package:go": "npx projen package:go",
    "package:js": "npx projen package:js",
    "post-compile": "npx projen post-compile",
    "post-upgrade": "npx projen post-upgrade",
    "pre-compile": "npx projen pre-compile",
    "release": "npx projen release",
    "test": "npx projen test",
    "test:watch": "npx projen test:watch",
    "unbump": "npx projen unbump",
    "upgrade": "npx projen upgrade",
    "watch": "npx projen watch",
    "projen": "npx projen"
  },
  "author": {
    "name": "TirushV",
    "email": "tirush.venamadala@fox.com",
    "organization": false
  },
  "devDependencies": {
    "@types/jest": "29",
    "@types/node": "^18",
    "@typescript-eslint/eslint-plugin": "^7",
    "@typescript-eslint/parser": "^7",
    "aws-cdk-lib": "2.152.0",
    "commit-and-tag-version": "^12",
    "constructs": "10.0.5",
    "eslint": "^8",
    "eslint-config-prettier": "^9.1.0",
    "eslint-import-resolver-typescript": "^3.6.1",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-prettier": "^5.2.1",
    "jest": "29",
    "jest-junit": "^15",
    "jsii": "~5.4.0",
    "jsii-diff": "^1.103.1",
    "jsii-docgen": "^10.5.0",
    "jsii-pacmak": "^1.103.1",
    "jsii-rosetta": "~5.4.0",
    "prettier": "^3.3.3",
    "projen": "0.87.2",
    "ts-jest": "29",
    "ts-node": "^10.9.2",
    "typescript": "^5.4.5"
  },
  "peerDependencies": {
    "aws-cdk-lib": "2.152.0",
    "constructs": "^10.0.5"
  },
  "dependencies": {
    "@aws-cdk/aws-lambda-python-alpha": "^2.152.0-alpha.0"
  },
  "keywords": [
    "cdk"
  ],
  "engines": {
    "node": ">= 18.20.2"
  },
  "main": "lib/index.js",
  "license": "Apache-2.0",
  "publishConfig": {
    "registry": "https://npm.pkg.github.com/"
  },
  "version": "0.0.0",
  "jest": {
    "coverageProvider": "v8",
    "testMatch": [
      "<rootDir>/@(src|test)/**/*(*.)@(spec|test).ts?(x)",
      "<rootDir>/@(src|test)/**/__tests__/**/*.ts?(x)",
      "<rootDir>/@(projenrc)/**/*(*.)@(spec|test).ts?(x)",
      "<rootDir>/@(projenrc)/**/__tests__/**/*.ts?(x)"
    ],
    "clearMocks": true,
    "collectCoverage": true,
    "coverageReporters": [
      "json",
      "lcov",
      "clover",
      "cobertura",
      "text"
    ],
    "coverageDirectory": "coverage",
    "coveragePathIgnorePatterns": [
      "/node_modules/"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/"
    ],
    "watchPathIgnorePatterns": [
      "/node_modules/"
    ],
    "reporters": [
      "default",
      [
        "jest-junit",
        {
          "outputDirectory": "test-reports"
        }
      ]
    ],
    "transform": {
      "^.+\\.[t]sx?$": [
        "ts-jest",
        {
          "tsconfig": "tsconfig.dev.json"
        }
      ]
    }
  },
  "types": "lib/index.d.ts",
  "stability": "stable",
  "jsii": {
    "outdir": "dist",
    "targets": {
      "go": {
        "moduleName": "github.com/bclxyz/custom-cdk-constructs",
        "packageName": "bclxyzconstructsgo"
      }
    },
    "tsc": {
      "outDir": "lib",
      "rootDir": "src"
    }
  },
  "//": "~~ Generated by projen. To modify, edit .projenrc.ts and run \"npx projen\"."
}

```

**Comment by mrgrain** [comment]
Thanks. That looks all good. `cdkVersionPinning: true` should not be needed.

This works for me as expected:

```console
npx projen new awscdk-construct --cdk-version 2.152.0
yarn why aws-cdk-lib
```

```
=> Found "aws-cdk-lib@2.152.0"
info Has been hoisted to "aws-cdk-lib"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "97.46MB"
info Disk size with unique dependencies: "146.39MB"
info Disk size with transitive dependencies: "148.95MB"
info Number of shared dependencies: 28
```

What does `yarn why aws-cdk-lib` output for you?

**Comment by TirushV** [comment]
Getting same output like above

**Comment by TirushV** [comment]
Fixed the issue. Thank you so much for the quick help

**Comment by mrgrain** [comment]
Well that's what we are trying to find out.

projen doesn't really do anything in that regard. projen only defines the dependency constraints in `package.json`. We can see that these are as expected and `yarn why` output shows we have the right version of `aws-cdk-lib`. 

When you build the project a tool called `jsii` is creating an assembly file that basically says `ApiGatewayStackProps` extends `StackProps` form `aws-cdk-lib`. Another tool called `jsii-docgen` is then using this information to generated the actual file. Somewhere in this proces, something accidentally uses the wrong version of `aws-cdk-lib`.

**Comment by mrgrain** [comment]
> Fixed the issue. Thank you so much for the quick help

What was the issue in the end? I actually managed to reproduce this on my machine and it's very confusing to me!
