### ISSUE TITLE
GithubWorkflow.get_job('job_id') not working

### ISSUE THREAD

**Issue by JovanDordevic** [projen/projen#4011]
I am using python to try and interact with a github workflow created in typescript, through JSII. 
I am using projen 'v0.90.6` (but have observed the same issue even as early as `v0.74.8`)

I am trying to do the following (in python):
```python 
...
project = PythonProject(...)

on_pr_closed = project.github.try_find_workflow("on-pr-closed")
build_job = on_pr_closed.get_job('build')
print(build_job)
```

The error I'm getting is:

```
jsii.errors.JavaScriptError: 
  @jsii/kernel.SerializationError: Of property Object.uses: Unable to serialize value as string
  ├── 🛑 Failing value is undefined
  ╰── 🔍 Failure reason(s):
      ╰─ A value is required (type is non-optional)
      at Object.process (/private/var/folders/qz/5m38p8jd36q3fv0bkrv70ypw0000gn/T/tmpnl5f4t2v/lib/program.js:10486:19)
      at Kernel._Kernel_fromSandbox (/private/var/folders/qz/5m38p8jd36q3fv0bkrv70ypw0000gn/T/tmpnl5f4t2v/lib/program.js:9466:25)
      at Kernel.get (/private/var/folders/qz/5m38p8jd36q3fv0bkrv70ypw0000gn/T/tmpnl5f4t2v/lib/program.js:8846:103)
      at KernelHost.processRequest (/private/var/folders/qz/5m38p8jd36q3fv0bkrv70ypw0000gn/T/tmpnl5f4t2v/lib/program.js:10718:36)
      at KernelHost.run (/private/var/folders/qz/5m38p8jd36q3fv0bkrv70ypw0000gn/T/tmpnl5f4t2v/lib/program.js:10678:22)
      at Immediate._onImmediate (/private/var/folders/qz/5m38p8jd36q3fv0bkrv70ypw0000gn/T/tmpnl5f4t2v/lib/program.js:10679:46)
      at process.processImmediate (node:internal/timers:476:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jovan/Dev/my-project/.projenrc.py", line 78, in <module>
    build_job = on_pr_closed.get_job('build')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jovan/Dev/my-project/venv/lib/python3.11/site-packages/projen/github/__init__.py", line 4274, in get_job
    return typing.cast(typing.Union[_JobCallingReusableWorkflow_12ad1018, _Job_20ffcf45], jsii.invoke(self, "getJob", [id]))
                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jovan/Dev/my-project/venv/lib/python3.11/site-packages/jsii/_kernel/__init__.py", line 149, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jovan/Dev/my-project/venv/lib/python3.11/site-packages/jsii/_kernel/__init__.py", line 139, in _recursize_dereference
    return _reference_map.resolve_reference(kernel, d)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jovan/Dev/my-project/venv/lib/python3.11/site-packages/jsii/_reference_map.py", line 121, in resolve
    **{
      ^
  File "/Users/jovan/Dev/my-project/venv/lib/python3.11/site-packages/jsii/_reference_map.py", line 122, in <dictcomp>
    python_name: kernel.get(remote_struct, jsii_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jovan/Dev/my-project/venv/lib/python3.11/site-packages/jsii/_kernel/__init__.py", line 149, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jovan/Dev/my-project/venv/lib/python3.11/site-packages/jsii/_kernel/__init__.py", line 360, in get
    response = self.provider.get(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/jovan/Dev/my-project/venv/lib/python3.11/site-packages/jsii/_kernel/providers/process.py", line 368, in get
    return self._process.send(request, GetResponse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jovan/Dev/my-project/venv/lib/python3.11/site-packages/jsii/_kernel/providers/process.py", line 342, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: Of property Object.uses: Unable to serialize value as string
├── 🛑 Failing value is undefined
╰── 🔍 Failure reason(s):
    ╰─ A value is required (type is non-optional)
👾 Synthesis failed: Task "default" failed when executing "poetry run python .projenrc.py" (cwd: /Users/jovan/Dev/my-project)
```

Finding the workflow object itself works fine, and printing out its `__dict__` works fine as well. See below:
```python
print(f'DEBUG {on_pr_closed=}')
print(f'DEBUG {on_pr_closed.__dict__}')
print(f'DEBUG {dir(on_pr_closed)}')
print(f'DEBUG {on_pr_closed.name}')
print(f'DEBUG {on_pr_closed.node}')
print(f'DEBUG {on_pr_closed.on}')

# Outputs the following:

DEBUG on_pr_closed=<projen.github.GithubWorkflow object at 0x103b9e310>
DEBUG {'__jsii_ref__': ObjRef(ref='projen.github.GithubWorkflow@10005', interfaces=None)}
DEBUG ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__jsii_declared_type__', '__jsii_ifaces__', '__jsii_proxy_class__', '__jsii_ref__', '__jsii_type__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__protocol_attrs__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'add_job', 'add_jobs', 'concurrency', 'file', 'get_job', 'is_component', 'is_construct', 'name', 'node', 'on', 'post_synthesize', 'pre_synthesize', 'project', 'projen_credentials', 'remove_job', 'run_name', 'synthesize', 'to_string', 'update_job', 'update_jobs']
DEBUG on-pr-closed
DEBUG <constructs.Node object at 0x104b7cf10>
DEBUG <bound method GithubWorkflow.on of <projen.github.GithubWorkflow object at 0x103b9e310>>
````

I have tried to track the issue, and found that the following is being excecuted in JSII:
```python
class GithubWorkflow(
    _Component_2b0ad27f,
    metaclass=jsii.JSIIMeta,
    jsii_type="projen.github.GithubWorkflow",
):
    '''(experimental) Workflow for GitHub.

    A workflow is a configurable automated process made up of one or more jobs.

    :see: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
    :stability: experimental
    '''

    .... other methods .....

    @jsii.member(jsii_name="getJob")
    def get_job(
        self,
        id: builtins.str,
    ) -> typing.Union[_JobCallingReusableWorkflow_12ad1018, _Job_20ffcf45]:
        '''(experimental) Get a single job from the workflow.

        :param id: The job name (unique within the workflow).

        :stability: experimental
        '''
        if __debug__:
            type_hints = typing.get_type_hints(_typecheckingstub__f6eb2f09bb8f2d945c8f2826934c657ba552c34bd0514dcd4dfea5bae7172af5)
            check_type(argname="argument id", value=id, expected_type=type_hints["id"])
        return typing.cast(typing.Union[_JobCallingReusableWorkflow_12ad1018, _Job_20ffcf45], jsii.invoke(self, "getJob", [id]))


```

I have found that this error happens exactly when calling `typing.cast(typing.Union[_JobCallingReusableWorkflow_12ad1018, _Job_20ffcf45], jsii.invoke(self, "getJob", [id]))`, which leads me to believe the issue is not within my code but in how the jsii mapping is made

**Comment by JovanDordevic** [comment]
@mrgrain Hello, apologies for tagging you directly (I saw that you are one of the biggest contributors to this project and thought maybe you could point me where to go). I opened this issue over a month ago and no one looked at it yet (whereas I see other issues opened more recently are at least being tagged by contributors as bugs, features etc. How do I go about increasing visibility for this?

**Comment by mrgrain** [comment]
Hi @JovanDordevic No worries. This is likely not a projen-specific issue, but a problem with jsii. We will need to investigate some more here. I agree this is not intended behavior, worst case a more descriptive error should be thrown.

**Comment by bhrutledge** [comment]
> This is likely not a projen-specific issue, but a problem with jsii. We will need to investigate some more here. I agree this is not intended behavior, worst case a more descriptive error should be thrown.

@mrgrain This continues to be a challenge for us (@JovanDordevic and I are colleagues). Is there anything we can do to help with investigation/resolution?
