### ISSUE TITLE
npx projen build is broken in latest

### ISSUE THREAD

**Issue by pgollucci** [projen/projen#478]
npx projen build
.........
 PASS  lib/__tests__/new.test.js (14.711 s)

Test Suites: 32 passed, 32 total
Tests:       1161 passed, 1161 total
Snapshots:   44 passed, 44 total
Time:        30.471 s
Ran all test suites.
🤖 build » test » eslint | eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src src/__tests__ build-tools
🤖 build » package | jsii-pacmak
[jsii-pacmak] [WARN] Exception occurred, not cleaning up 
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/pgollucci/src/github.com/projen/projen/node_modules/yargs/package.json
    at new NodeError (node:internal/errors:278:15)
    at throwExportsNotFound (node:internal/modules/esm/resolve:321:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:546:3)
    at resolveExports (node:internal/modules/cjs/loader:473:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:513:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:911:27)
    at Function.resolve (node:internal/modules/cjs/helpers:98:19)
    at Object.resolveDependencyDirectory (/Users/pgollucci/src/github.com/projen/projen/node_modules/jsii-pacmak/lib/util.js:18:33)
    at /Users/pgollucci/src/github.com/projen/projen/node_modules/jsii-pacmak/lib/dependency-graph.js:44:36
    at Array.map (<anonymous>)
🤖 Task "build » package" failed when executing "jsii-pacmak" (cwd: /Users/pgollucci/src/github.com/projen/projen)
npm ERR! code 1
npm ERR! path /Users/pgollucci/src/github.com/projen/projen
npm ERR! command failed
npm ERR! command sh -c projen build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pgollucci/.npm/_logs/2021-01-09T16_15_10_801Z-debug.log

git log
* '6b55631 - (HEAD -> master, tag: v0.14.4, origin/master, origin/HEAD) chore(release): 0.14.4 (17 hours ago) <Auto-bump>'

**Comment by pgollucci** [comment]
This was introduced in v0.14.0

**Comment by pgollucci** [comment]
just a note jsii-packmak went from 1.15.0 to 1.16.0
