### ISSUE TITLE
bug: tests failing for upgrade-dependencies.test.ts

### ISSUE THREAD

**Issue by Hunter-Thompson** [projen/projen#805]
https://github.com/projen/projen/blob/2c99dc6540bb39dda1856a94421d0d9e22b43774/src/__tests__/upgrade-dependencies.test.ts#L7-L10

We are creating a test project, which by default creates the `.github/workflows/upgrade-dependencies.yml` file, we are also creating a new instance of `UpgradeDependencies`, which causes the test to fail with the following error because the file already exists. Im assuming.

```
Summary of all failing tests
FAIL lib/__tests__/upgrade-dependencies.test.js
  ● default options

    there is already a file under .github/workflows/upgrade-dependencies.yml

      80 |     const existing = project.root.tryFindFile(this.absolutePath);
      81 |     if (existing && existing !== this) {
    > 82 |       throw new Error(`there is already a file under ${path.relative(project.root.outdir, this.absolutePath)}`);
         |             ^
      83 |     }
      84 |
      85 |     const gitignore = options.editGitignore ?? true;

      at new FileBase (src/file.ts:82:13)
      at new ObjectFile (src/object-file.ts:58:5)
      at new YamlFile (src/yaml.ts:16:5)
      at new GithubWorkflow (src/github/workflows.ts:15:17)
      at GitHub.addWorkflow (src/github/github.ts:47:12)
      at UpgradeDependencies.createWorkflow (src/upgrade-dependencies.ts:133:29)
      at new UpgradeDependencies (src/upgrade-dependencies.ts:100:28)
      at Object.<anonymous>.test (src/__tests__/upgrade-dependencies.test.ts:10:3)

  ● custom options

    there is already a file under .github/workflows/upgrade-dependencies.yml

      80 |     const existing = project.root.tryFindFile(this.absolutePath);
      81 |     if (existing && existing !== this) {
    > 82 |       throw new Error(`there is already a file under ${path.relative(project.root.outdir, this.absolutePath)}`);
         |             ^
      83 |     }
      84 |
      85 |     const gitignore = options.editGitignore ?? true;

      at new FileBase (src/file.ts:82:13)
      at new ObjectFile (src/object-file.ts:58:5)
      at new YamlFile (src/yaml.ts:16:5)
      at new GithubWorkflow (src/github/workflows.ts:15:17)
      at GitHub.addWorkflow (src/github/github.ts:47:12)
      at UpgradeDependencies.createWorkflow (src/upgrade-dependencies.ts:133:29)
      at new UpgradeDependencies (src/upgrade-dependencies.ts:100:28)
      at Object.<anonymous>.test (src/__tests__/upgrade-dependencies.test.ts:22:3)
```

How to test? 

- Run build on your latest projen fork.

[Sample build](https://github.com/projen/projen/pull/806/checks?check_run_id=2614216610)

**Comment by Hunter-Thompson** [comment]
@iliapolo, could you have a look at this?

**Comment by Hunter-Thompson** [comment]
The obvious solution for the default options would be :

```
diff --git a/src/__tests__/upgrade-dependencies.test.ts b/src/__tests__/upgrade-dependencies.test.ts
index 5f7d7e2..10a2be6 100644
--- a/src/__tests__/upgrade-dependencies.test.ts
+++ b/src/__tests__/upgrade-dependencies.test.ts
@@ -7,7 +7,6 @@ test('default options', () => {
   const project = createProject({
     projenUpgradeSecret: 'PROJEN_SECRET',
   });
-  new UpgradeDependencies(project);
 
   const snapshot = synthSnapshot(project);
   expect(snapshot['.github/workflows/upgrade-dependencies.yml']).toBeDefined();
   ```
But for custom options it might be a big tricky.
