### ISSUE TITLE
Creating from external module doesn't work if developing locally

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#879]
Following the updated CONTRIBUTING instructions [here](https://github.com/projen/projen/blob/main/CONTRIBUTING.md#testing-against-local-projects), if I try running in an empty directory:

```bash
$ yarn link projen  # (assuming a locally built version of projen has already been linked)
$ npx projen new --from cdk-appsync-project
```

then the setup fails with the error "Error: Cannot find module 'cdk-appsync-project/.jsii'". Full stack trace below:

<details>

```
$ npx projen new --from cdk-appsync-project
npx: installed 87 in 4.61s
🤖 installing external module cdk-appsync-project...
🤖 yarn add --modules-folder=/Users/rybickic/Developer/projen-test/node_modules --silent --no-lockfile --dev cdk-appsync-project
projen new [PROJECT-TYPE] [OPTIONS]

Creates a new projen project

Commands:
  projen new awscdk-app-ts     AWS CDK app in TypeScript.
  projen new awscdk-construct  AWS CDK construct library project.
  projen new cdk8s-app-ts      CDK8s app in TypeScript.
  projen new cdk8s-construct   CDK8s construct library project.
  projen new cdktf-construct   CDKTF construct library project.
  projen new java              Java project.
  projen new jsii              Multi-language jsii library project.
  projen new nextjs            Next.js project without TypeScript.
  projen new nextjs-ts         Next.js project with TypeScript.
  projen new node              Node.js project.
  projen new project           Base project.
  projen new python            Python project.
  projen new react             React project without TypeScript.
  projen new react-ts          React project with TypeScript.
  projen new typescript        TypeScript project.
  projen new typescript-app    TypeScript app.

Positionals:
  PROJECT-TYPE  optional only when --from is used and there is a single project type
                in the external module                                        [string]

Options:
      --post      Run post-synthesis steps such as installing dependencies. Use
                  --no-post to skip                          [boolean] [default: true]
  -w, --watch     Keep running and resynthesize when projenrc changes
                                                            [boolean] [default: false]
      --debug     Debug logs                                [boolean] [default: false]
      --rc        path to .projenrc.js file
              [string] [default: "/Users/rybickic/Developer/projen-test/.projenrc.js"]
      --help      Show help                                                  [boolean]
      --synth     Synthesize after creating .projenrc.js     [boolean] [default: true]
      --comments  Include commented out options in .projenrc.js (use --no-comments to
                  disable)                                   [boolean] [default: true]
  -f, --from      External jsii npm module to create project from. Supports any
                  package spec supported by yarn (such as "my-pack@^2.0")     [string]
      --git       Run `git init` and create an initial commit (use --no-git to
                  disable)                                   [boolean] [default: true]

Examples:
  projen new awscdk-app-ts         Creates a new project of built-in type
                                   "awscdk-app-ts"
  projen new --from projen-vue@^2  Creates a new project from an external module
                                   "projen-vue" with the specified version

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'cdk-appsync-project/.jsii'
Require stack:
- /Users/rybickic/Developer/projen/lib/inventory.js
- /Users/rybickic/Developer/projen/lib/javascript/render-options.js
- /Users/rybickic/Developer/projen/lib/javascript/projenrc.js
- /Users/rybickic/Developer/projen/lib/node-project.js
- /Users/rybickic/Developer/projen/lib/typescript.js
- /Users/rybickic/Developer/projen/lib/awscdk-app-ts.js
- /Users/rybickic/Developer/projen/lib/index.js
- /Users/rybickic/Developer/projen-test/node_modules/cdk-appsync-project/lib/index.js
- /Users/rybickic/.npm/_npx/76066/lib/node_modules/projen/lib/cli/cmds/new.js
- /Users/rybickic/.npm/_npx/76066/lib/node_modules/projen/node_modules/yargs/index.cjs
- /Users/rybickic/.npm/_npx/76066/lib/node_modules/projen/lib/cli/index.js
- /Users/rybickic/.npm/_npx/76066/lib/node_modules/projen/bin/projen
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at readJsiiManifest (/Users/rybickic/Developer/projen/lib/inventory.js:90:38)
    at Object.resolveProjectType (/Users/rybickic/Developer/projen/lib/inventory.js:52:22)
    at Object.resolveNewProject (/Users/rybickic/Developer/projen/lib/javascript/render-options.js:23:28)
    at new Project (/Users/rybickic/Developer/projen/lib/project.js:31:44)
    at new NodeProject (/Users/rybickic/Developer/projen/lib/node-project.js:38:9)
    at new TypeScriptProject (/Users/rybickic/Developer/projen/lib/typescript.js:22:9)
    at new TypeScriptAppProject (/Users/rybickic/Developer/projen/lib/typescript.js:262:9)
    at new AwsCdkTypeScriptApp (/Users/rybickic/Developer/projen/lib/awscdk-app-ts.js:34:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/rybickic/Developer/projen/lib/inventory.js',
    '/Users/rybickic/Developer/projen/lib/javascript/render-options.js',
    '/Users/rybickic/Developer/projen/lib/javascript/projenrc.js',
    '/Users/rybickic/Developer/projen/lib/node-project.js',
    '/Users/rybickic/Developer/projen/lib/typescript.js',
    '/Users/rybickic/Developer/projen/lib/awscdk-app-ts.js',
    '/Users/rybickic/Developer/projen/lib/index.js',
    '/Users/rybickic/Developer/projen-test/node_modules/cdk-appsync-project/lib/index.js',
    '/Users/rybickic/.npm/_npx/76066/lib/node_modules/projen/lib/cli/cmds/new.js',
    '/Users/rybickic/.npm/_npx/76066/lib/node_modules/projen/node_modules/yargs/index.cjs',
    '/Users/rybickic/.npm/_npx/76066/lib/node_modules/projen/lib/cli/index.js',
    '/Users/rybickic/.npm/_npx/76066/lib/node_modules/projen/bin/projen'
  ]
}
```
</details>

Running the command without `yarn link projen` before succeeds, and likewise, if I link but use a built-in project type instead (like `npx projen new node`) then it also succeeds.

Low-priority issue.

----

A workaround is just to run `npx projen new --from cdk-appsync-project` without linking, and then remove the appropriate lines in package.json that specify the `projen` version, and then run `yarn link projen` and `npx projen` (and the `package.json` should automatically update with `"projen": "^0.0.0"`).

**Comment by kcwinner** [comment]
I should validate the `cdk-appsync-project` works with the latest version of projen as well.

**Comment by eladb** [comment]
@Chriscbr is this still relevant?

**Comment by kcwinner** [comment]
Still relevant. I'll see if I can get to it this week / weekend
