### ISSUE TITLE
Synth breaks for JSII projects with TS projenrc file after build

### ISSUE THREAD

**Issue by akash1810** [projen/projen#948]
There appears to be an issue with a TypeScript projenrc file (`.projenrc.ts`), at least in a JSII project (not tested against other project types).

It ultimately results in this when trying to resynth a project:

```console
➜ npx projen
🤖 default | env: PATH=/Users/akash_askoolu...
🤖 default | ts-node .projenrc.ts

/Users/akash_askoolum/code/temp/projen-ts/node_modules/ts-node/src/index.ts:755
          throw new TypeError(`${relative(cwd, fileName)}: Emit skipped`)
                ^
TypeError: .projenrc.ts: Emit skipped
    at getOutput (/Users/akash_askoolum/code/temp/projen-ts/node_modules/ts-node/src/index.ts:755:17)
    at Object.compile (/Users/akash_askoolum/code/temp/projen-ts/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/akash_askoolum/code/temp/projen-ts/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/akash_askoolum/code/temp/projen-ts/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at main (/Users/akash_askoolum/code/temp/projen-ts/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/Users/akash_askoolum/code/temp/projen-ts/node_modules/ts-node/src/bin.ts:288:3)
🤖 Synthesis failed: Task "default" failed when executing "ts-node .projenrc.ts" (cwd: /Users/akash_askoolum/code/temp/projen-ts)
```

## How to reproduce
We think this is the minimum way to reproduce:

1. Create a new project
  ```
  npx projen new jsii --projenrc-ts
  ```
2. Synth (this is just to show that it works)
  ```
  npx projen
  ```
3. Build the project
  ```
  npx projen build
  ```
4. Synth (this fails)
  ```
  npx projen
  ```

We've seen that a `tsconfig.json` is created during step 3, removing this seems to make synthesis work again, until of course a build is run again.

Node version: 14.17.3.

**Comment by Chriscbr** [comment]
Interesting - sp it looks like when we run `npx projen` in step 4, it automatically uses the `tsconfig.json` that was generated for the main project - and the default `tsconfig.json` doesn't include `.projenrc.ts` in its "include" files, so it errors.

I think we want `.projenrc.ts` to get processed by ts-node without using the tsconfig.json settings, since the tsconfig.json is really meant to be for the user's TypeScript source code, not the projenrc.ts.

**Comment by akash1810** [comment]
Such fast work! Thanks @Chriscbr !
